/* Generated By:JJTree: Do not edit this line. CPPASTtype_name.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTtype_name extends CPPSimpleNode {
  public CPPASTtype_name(int id) {
    super(id);
  }

  public CPPASTtype_name(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9450cbd42c7669be9b6be7099ed10233 (do not edit this line) */
