/* Generated By:JJTree: Do not edit this line. CPPASTlabeled_statement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTlabeled_statement extends CPPSimpleNode {
  public CPPASTlabeled_statement(int id) {
    super(id);
  }

  public CPPASTlabeled_statement(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bf56542b555c3caff1298262ed6931de (do not edit this line) */
