/* Generated By:JJTree: Do not edit this line. CPPASTclass_specifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTclass_specifier extends CPPSimpleNode {
  public CPPASTclass_specifier(int id) {
    super(id);
  }

  public CPPASTclass_specifier(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=173ca904084496076bd58fdead026908 (do not edit this line) */
