/* Generated By:JJTree: Do not edit this line. CPPASTcast_expression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTcast_expression extends CPPSimpleNode {
  public CPPASTcast_expression(int id) {
    super(id);
  }

  public CPPASTcast_expression(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fb7097dff71bc03e45e9acbf494eadb3 (do not edit this line) */
