/* Generated By:JJTree: Do not edit this line. CPPASTfunction_definition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTfunction_definition extends CPPSimpleNode {
  public CPPASTfunction_definition(int id) {
    super(id);
  }

  public CPPASTfunction_definition(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e3f4871858fca84d247281108531ceda (do not edit this line) */
