/* Generated By:JJTree: Do not edit this line. CPPASTtemplate_argument.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTtemplate_argument extends CPPSimpleNode {
  public CPPASTtemplate_argument(int id) {
    super(id);
  }

  public CPPASTtemplate_argument(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b2e5914ce8d6de07c5afcca0c0645246 (do not edit this line) */
