/* Generated By:JJTree: Do not edit this line. CPPASTextern_builtin_type_specifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTextern_builtin_type_specifier extends CPPSimpleNode {
  public CPPASTextern_builtin_type_specifier(int id) {
    super(id);
  }

  public CPPASTextern_builtin_type_specifier(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bc2dcb976967ab2c9106f86c7d8d57bb (do not edit this line) */
