/* Generated By:JJTree: Do not edit this line. CPPASTsuperclass_init.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTsuperclass_init extends CPPSimpleNode {
  public CPPASTsuperclass_init(int id) {
    super(id);
  }

  public CPPASTsuperclass_init(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=26b2ead3ffa6c0f42a2ffcc8c1177978 (do not edit this line) */
