/* Generated By:JJTree: Do not edit this line. CPPASTsimple_type_specifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTsimple_type_specifier extends CPPSimpleNode {
  public CPPASTsimple_type_specifier(int id) {
    super(id);
  }

  public CPPASTsimple_type_specifier(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=330d7aa762e9d22fa5980e1566e5defe (do not edit this line) */
