/* Generated By:JJTree: Do not edit this line. CPPASTinit_declarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTinit_declarator extends CPPSimpleNode {
  public CPPASTinit_declarator(int id) {
    super(id);
  }

  public CPPASTinit_declarator(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1d8ea8c3ec5325b533f1a11d6639504c (do not edit this line) */
