/* Generated By:JJTree: Do not edit this line. CPPASTconstant.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTconstant extends CPPSimpleNode {
  public CPPASTconstant(int id) {
    super(id);
  }

  public CPPASTconstant(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=85fca469a53671fdd6e823c1d180e7b7 (do not edit this line) */
