/* Generated By:JJTree: Do not edit this line. CPPASTfunction_direct_declarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTfunction_direct_declarator extends CPPSimpleNode {
  public CPPASTfunction_direct_declarator(int id) {
    super(id);
  }

  public CPPASTfunction_direct_declarator(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d093832f6b4d5be225156f774ec12b09 (do not edit this line) */
