/* Generated By:JJTree: Do not edit this line. CPPASTctor_definition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTctor_definition extends CPPSimpleNode {
  public CPPASTctor_definition(int id) {
    super(id);
  }

  public CPPASTctor_definition(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9b1a28c4c15cf934197982777b396dc4 (do not edit this line) */
