/* Generated By:JJTree: Do not edit this line. CPPASTscope_override_lookahead.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTscope_override_lookahead extends CPPSimpleNode {
  public CPPASTscope_override_lookahead(int id) {
    super(id);
  }

  public CPPASTscope_override_lookahead(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8c167c0cac7caa46ca66f2a65b4f9552 (do not edit this line) */
