/* Generated By:JJTree: Do not edit this line. CPPASTnew_initializer.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTnew_initializer extends CPPSimpleNode {
  public CPPASTnew_initializer(int id) {
    super(id);
  }

  public CPPASTnew_initializer(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=175f15967361fe34cdf58d7823f7e174 (do not edit this line) */
