/* Generated By:JJTree: Do not edit this line. CPPASTadditive_expression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTadditive_expression extends CPPSimpleNode {
  public CPPASTadditive_expression(int id) {
    super(id);
  }

  public CPPASTadditive_expression(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ac70f2b0278bf8bb3c6ed1c2f9feafdc (do not edit this line) */
