/* Generated By:JJTree: Do not edit this line. CPPASTenumerator_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTenumerator_list extends CPPSimpleNode {
  public CPPASTenumerator_list(int id) {
    super(id);
  }

  public CPPASTenumerator_list(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3a32d4b39d1c2d4ffd870a027a586433 (do not edit this line) */
