/* Generated By:JJTree: Do not edit this line. CPPASTconversion_function_decl_or_def.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTconversion_function_decl_or_def extends CPPSimpleNode {
  public CPPASTconversion_function_decl_or_def(int id) {
    super(id);
  }

  public CPPASTconversion_function_decl_or_def(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=96b10293a75eba4bc7ede593b5b8f038 (do not edit this line) */
