/* Generated By:JJTree: Do not edit this line. CPPASTnew_declarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTnew_declarator extends CPPSimpleNode {
  public CPPASTnew_declarator(int id) {
    super(id);
  }

  public CPPASTnew_declarator(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9bfb679124a988cd1b590d6212110225 (do not edit this line) */
