/* Generated By:JJTree: Do not edit this line. CPPASTiteration_statement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTiteration_statement extends CPPSimpleNode {
  public CPPASTiteration_statement(int id) {
    super(id);
  }

  public CPPASTiteration_statement(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=536f04c48de5aaf336c76cddf68b0705 (do not edit this line) */
