/* Generated By:JJTree: Do not edit this line. CPPASTexpression_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTexpression_list extends CPPSimpleNode {
  public CPPASTexpression_list(int id) {
    super(id);
  }

  public CPPASTexpression_list(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fcd8df33736fab78855e61ea95232d88 (do not edit this line) */
