/* Generated By:JJTree: Do not edit this line. CPPASTrelational_expression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTrelational_expression extends CPPSimpleNode {
  public CPPASTrelational_expression(int id) {
    super(id);
  }

  public CPPASTrelational_expression(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bba3972609910d1d9b3d559b23dc40e3 (do not edit this line) */
