/* Generated By:JJTree: Do not edit this line. CPPASTtemplate_argument_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTtemplate_argument_list extends CPPSimpleNode {
  public CPPASTtemplate_argument_list(int id) {
    super(id);
  }

  public CPPASTtemplate_argument_list(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d4f7a3d2dbaf1af3d610faf2c98235d9 (do not edit this line) */
