/* Generated By:JJTree: Do not edit this line. CPPASTid_expression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTid_expression extends CPPSimpleNode {
  public CPPASTid_expression(int id) {
    super(id);
  }

  public CPPASTid_expression(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d12263edf5a5ec5f20acf454915a4512 (do not edit this line) */
