/* Generated By:JJTree: Do not edit this line. CPPASTparameter_declaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTparameter_declaration extends CPPSimpleNode {
  public CPPASTparameter_declaration(int id) {
    super(id);
  }

  public CPPASTparameter_declaration(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4b53d18f94166516644e7e5e7a05ac1b (do not edit this line) */
