/* Generated By:JJTree: Do not edit this line. CPPASTtemplate_parameter_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTtemplate_parameter_list extends CPPSimpleNode {
  public CPPASTtemplate_parameter_list(int id) {
    super(id);
  }

  public CPPASTtemplate_parameter_list(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c66124af4dcb5017a8624813d1d4c943 (do not edit this line) */
