/* Generated By:JJTree: Do not edit this line. CPPASTfunction_declarator_lookahead.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTfunction_declarator_lookahead extends CPPSimpleNode {
  public CPPASTfunction_declarator_lookahead(int id) {
    super(id);
  }

  public CPPASTfunction_declarator_lookahead(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cab9aae146f48a6a6e1a1874ad5adcc2 (do not edit this line) */
