/* Generated By:JJTree: Do not edit this line. CPPASTfunction_declarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTfunction_declarator extends CPPSimpleNode {
  public CPPASTfunction_declarator(int id) {
    super(id);
  }

  public CPPASTfunction_declarator(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c644a35fd5aed4069c5e73080d6d61be (do not edit this line) */
