/* Generated By:JJTree: Do not edit this line. CPPASTfunc_decl_def.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTfunc_decl_def extends CPPSimpleNode {
  public CPPASTfunc_decl_def(int id) {
    super(id);
  }

  public CPPASTfunc_decl_def(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=187f3c0457bd24f637f38fbd0aa45210 (do not edit this line) */
