/* Generated By:JJTree: Do not edit this line. CPPASTexclusive_or_expression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTexclusive_or_expression extends CPPSimpleNode {
  public CPPASTexclusive_or_expression(int id) {
    super(id);
  }

  public CPPASTexclusive_or_expression(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=14afdf7cf6c63df8649a557069b02999 (do not edit this line) */
