/* Generated By:JJTree: Do not edit this line. CPPASTparameter_declaration_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTparameter_declaration_list extends CPPSimpleNode {
  public CPPASTparameter_declaration_list(int id) {
    super(id);
  }

  public CPPASTparameter_declaration_list(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b5053ac011582e0b10cef601ad9a1863 (do not edit this line) */
