/* Generated By:JJTree: Do not edit this line. CPPASTequality_expression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTequality_expression extends CPPSimpleNode {
  public CPPASTequality_expression(int id) {
    super(id);
  }

  public CPPASTequality_expression(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1b830886cdfd1ad31448b036ed253b1b (do not edit this line) */
