/* Generated By:JJTree: Do not edit this line. CPPASTdelete_expression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTdelete_expression extends CPPSimpleNode {
  public CPPASTdelete_expression(int id) {
    super(id);
  }

  public CPPASTdelete_expression(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4bca3e7ede6c422a5524b0bb1d52160e (do not edit this line) */
