/* Generated By:JJTree: Do not edit this line. CPPASTlogical_or_expression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTlogical_or_expression extends CPPSimpleNode {
  public CPPASTlogical_or_expression(int id) {
    super(id);
  }

  public CPPASTlogical_or_expression(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2991d60d4bc617fc66fb59bb76a72bb5 (do not edit this line) */
