/* Generated By:JJTree: Do not edit this line. CPPASTtemplate_id.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTtemplate_id extends CPPSimpleNode {
  public CPPASTtemplate_id(int id) {
    super(id);
  }

  public CPPASTtemplate_id(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f70b697a8eb698b851a90a6d2a4483cd (do not edit this line) */
