/* Generated By:JJTree: Do not edit this line. CPPASTctor_declarator_lookahead.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTctor_declarator_lookahead extends CPPSimpleNode {
  public CPPASTctor_declarator_lookahead(int id) {
    super(id);
  }

  public CPPASTctor_declarator_lookahead(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7136557715a61781943b9a6f0cb9f407 (do not edit this line) */
