/* Generated By:JJTree: Do not edit this line. CPPASTctor_initializer.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTctor_initializer extends CPPSimpleNode {
  public CPPASTctor_initializer(int id) {
    super(id);
  }

  public CPPASTctor_initializer(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=676c3a0208ebbdb3777a8109904de598 (do not edit this line) */
