/* Generated By:JJTree: Do not edit this line. CPPASTunary_expression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTunary_expression extends CPPSimpleNode {
  public CPPASTunary_expression(int id) {
    super(id);
  }

  public CPPASTunary_expression(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e6e7844553d1687dacad24915d6bc205 (do not edit this line) */
