/* Generated By:JJTree: Do not edit this line. CPPASTmember_declarator_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTmember_declarator_list extends CPPSimpleNode {
  public CPPASTmember_declarator_list(int id) {
    super(id);
  }

  public CPPASTmember_declarator_list(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=10dca65aa83d91b82f4f6c24744d9369 (do not edit this line) */
