/* Generated By:JJTree: Do not edit this line. CPPASTnew_expression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTnew_expression extends CPPSimpleNode {
  public CPPASTnew_expression(int id) {
    super(id);
  }

  public CPPASTnew_expression(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4f56a4bd7968d6811e76e59bbe6fd2bd (do not edit this line) */
