/* Generated By:JJTree: Do not edit this line. CPPASTqualified_id.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTqualified_id extends CPPSimpleNode {
  public CPPASTqualified_id(int id) {
    super(id);
  }

  public CPPASTqualified_id(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=82503e5072520c598e927d83b46b21e6 (do not edit this line) */
