/* Generated By:JJTree: Do not edit this line. CPPASTthrow_statement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTthrow_statement extends CPPSimpleNode {
  public CPPASTthrow_statement(int id) {
    super(id);
  }

  public CPPASTthrow_statement(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bcc17b14a3d5c24df7d005611dcca9e6 (do not edit this line) */
