/* Generated By:JJTree: Do not edit this line. CPPASTdeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTdeclaration extends CPPSimpleNode {
  public CPPASTdeclaration(int id) {
    super(id);
  }

  public CPPASTdeclaration(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ebb4562e0e118de05a7ee9b894eefa54 (do not edit this line) */
