/* Generated By:JJTree: Do not edit this line. CPPASTptr_operator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTptr_operator extends CPPSimpleNode {
  public CPPASTptr_operator(int id) {
    super(id);
  }

  public CPPASTptr_operator(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d4f32c40554784ab7eadee3ecdf0f84a (do not edit this line) */
