/* Generated By:JJTree: Do not edit this line. CPPASTjump_statement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTjump_statement extends CPPSimpleNode {
  public CPPASTjump_statement(int id) {
    super(id);
  }

  public CPPASTjump_statement(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6815dae8938177e869fa6a31b649809f (do not edit this line) */
