/* Generated By:JJTree: Do not edit this line. CPPASTcompound_statement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTcompound_statement extends CPPSimpleNode {
  public CPPASTcompound_statement(int id) {
    super(id);
  }

  public CPPASTcompound_statement(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cba620b0ec2afe8a32d72cc3cb4df6f5 (do not edit this line) */
