/* Generated By:JJTree: Do not edit this line. CPPASTexception_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTexception_list extends CPPSimpleNode {
  public CPPASTexception_list(int id) {
    super(id);
  }

  public CPPASTexception_list(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3623749c961d6749c000b8be352d1c7e (do not edit this line) */
