/* Generated By:JJTree: Do not edit this line. CPPASTdeclaration_specifiers.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTdeclaration_specifiers extends CPPSimpleNode {
  public CPPASTdeclaration_specifiers(int id) {
    super(id);
  }

  public CPPASTdeclaration_specifiers(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=58d713ef668252ec488c2d47d65831ca (do not edit this line) */
