/* Generated By:JJTree: Do not edit this line. CPPASTexternal_declaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTexternal_declaration extends CPPSimpleNode {
  public CPPASTexternal_declaration(int id) {
    super(id);
  }

  public CPPASTexternal_declaration(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3697ecd0eead229d4f00cfb57478b9db (do not edit this line) */
