/* Generated By:JJTree: Do not edit this line. CPPASTexception_declaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTexception_declaration extends CPPSimpleNode {
  public CPPASTexception_declaration(int id) {
    super(id);
  }

  public CPPASTexception_declaration(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5e6b0e8005047aa4abef1ac7bbe95ee9 (do not edit this line) */
