/* Generated By:JJTree: Do not edit this line. CPPASTdtor_declarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTdtor_declarator extends CPPSimpleNode {
  public CPPASTdtor_declarator(int id) {
    super(id);
  }

  public CPPASTdtor_declarator(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ac2fd5549a7b68bb27a00a5e546889f9 (do not edit this line) */
