/* Generated By:JJTree: Do not edit this line. CPPASTprimary_expression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTprimary_expression extends CPPSimpleNode {
  public CPPASTprimary_expression(int id) {
    super(id);
  }

  public CPPASTprimary_expression(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9152bda34114e1be43f442b2f799ffac (do not edit this line) */
