/* Generated By:JJTree: Do not edit this line. CPPASTaccess_specifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTaccess_specifier extends CPPSimpleNode {
  public CPPASTaccess_specifier(int id) {
    super(id);
  }

  public CPPASTaccess_specifier(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6d41afe24fcb198a075d0ec9b5fd330e (do not edit this line) */
