/* Generated By:JJTree: Do not edit this line. CPPASTSizeOfOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTSizeOfOperator extends CPPSimpleNode {
  public CPPASTSizeOfOperator(int id) {
    super(id);
  }

  public CPPASTSizeOfOperator(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6503972194b5a24b7c28a3a0a42d5046 (do not edit this line) */
