/* Generated By:JJTree: Do not edit this line. CPPASTbase_specifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTbase_specifier extends CPPSimpleNode {
  public CPPASTbase_specifier(int id) {
    super(id);
  }

  public CPPASTbase_specifier(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=78a6bd4307a5aecc7845fbffcbc3c5cf (do not edit this line) */
