/* Generated By:JJTree: Do not edit this line. CPPASTstorage_class_specifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTstorage_class_specifier extends CPPSimpleNode {
  public CPPASTstorage_class_specifier(int id) {
    super(id);
  }

  public CPPASTstorage_class_specifier(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1741682ec93342796be67605c2e37903 (do not edit this line) */
