/* Generated By:JJTree: Do not edit this line. CPPASTpm_expression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTpm_expression extends CPPSimpleNode {
  public CPPASTpm_expression(int id) {
    super(id);
  }

  public CPPASTpm_expression(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=09bd9199d066c520071b77089c10e6e0 (do not edit this line) */
