/* Generated By:JJTree: Do not edit this line. CPPASTabstract_declarator_suffix.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTabstract_declarator_suffix extends CPPSimpleNode {
  public CPPASTabstract_declarator_suffix(int id) {
    super(id);
  }

  public CPPASTabstract_declarator_suffix(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8800ed56e9ce60d79e821465eb64d735 (do not edit this line) */
