/* Generated By:JJTree: Do not edit this line. CPPASTmember_declarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTmember_declarator extends CPPSimpleNode {
  public CPPASTmember_declarator(int id) {
    super(id);
  }

  public CPPASTmember_declarator(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a8a655a0562697a8ca38da9e75a385fd (do not edit this line) */
