/* Generated By:JJTree: Do not edit this line. CPPASTbuiltin_type_specifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTbuiltin_type_specifier extends CPPSimpleNode {
  public CPPASTbuiltin_type_specifier(int id) {
    super(id);
  }

  public CPPASTbuiltin_type_specifier(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e5d09b1bb5c7c7ab6ebf5d637ff10d4e (do not edit this line) */
