/* Generated By:JJTree: Do not edit this line. CPPASTptr_to_member.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTptr_to_member extends CPPSimpleNode {
  public CPPASTptr_to_member(int id) {
    super(id);
  }

  public CPPASTptr_to_member(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=59ae0d26aff6bc8a945cef8bec0521f7 (do not edit this line) */
