/* Generated By:JJTree: Do not edit this line. CPPASTunary_operator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTunary_operator extends CPPSimpleNode {
  public CPPASTunary_operator(int id) {
    super(id);
  }

  public CPPASTunary_operator(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=19a10aed31bc876d08b3c482e9602482 (do not edit this line) */
