/* Generated By:JJTree: Do not edit this line. CPPASTdirect_declarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTdirect_declarator extends CPPSimpleNode {
  public CPPASTdirect_declarator(int id) {
    super(id);
  }

  public CPPASTdirect_declarator(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b4a940506141ae84f2c213e9826db0b7 (do not edit this line) */
