/* Generated By:JJTree: Do not edit this line. CPPASTdeclarator_suffixes.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTdeclarator_suffixes extends CPPSimpleNode {
  public CPPASTdeclarator_suffixes(int id) {
    super(id);
  }

  public CPPASTdeclarator_suffixes(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=88f2e2a095f77a058af2aec92f4b8e8f (do not edit this line) */
