/* Generated By:JJTree: Do not edit this line. CPPASTshift_expression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTshift_expression extends CPPSimpleNode {
  public CPPASTshift_expression(int id) {
    super(id);
  }

  public CPPASTshift_expression(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e604b9354740c5c12444b58b30aac106 (do not edit this line) */
