/* Generated By:JJTree: Do not edit this line. CPPASTexception_spec.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTexception_spec extends CPPSimpleNode {
  public CPPASTexception_spec(int id) {
    super(id);
  }

  public CPPASTexception_spec(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ce84d53efea8f8dc2dad966c459356f8 (do not edit this line) */
