/* Generated By:JJTree: Do not edit this line. CPPASTlinkage_specification.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTlinkage_specification extends CPPSimpleNode {
  public CPPASTlinkage_specification(int id) {
    super(id);
  }

  public CPPASTlinkage_specification(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f108da7f0f0561929370601ff526fcc9 (do not edit this line) */
