/* Generated By:JJTree: Do not edit this line. CPPASTmember_declaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTmember_declaration extends CPPSimpleNode {
  public CPPASTmember_declaration(int id) {
    super(id);
  }

  public CPPASTmember_declaration(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=58072293b834015fe2fbc9da07d4d7ae (do not edit this line) */
