/* Generated By:JJTree: Do not edit this line. CPPASTabstract_declarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTabstract_declarator extends CPPSimpleNode {
  public CPPASTabstract_declarator(int id) {
    super(id);
  }

  public CPPASTabstract_declarator(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2183cece138f8062b1ad458e9cfed07a (do not edit this line) */
