/* Generated By:JJTree: Do not edit this line. CPPASTtry_block.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTtry_block extends CPPSimpleNode {
  public CPPASTtry_block(int id) {
    super(id);
  }

  public CPPASTtry_block(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c708b6d786bd9b6ed00c1fbd4d906e92 (do not edit this line) */
