/* Generated By:JJTree: Do not edit this line. CPPASTscope_override.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTscope_override extends CPPSimpleNode {
  public CPPASTscope_override(int id) {
    super(id);
  }

  public CPPASTscope_override(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8171fe91d09f7049582335735b1f7173 (do not edit this line) */
