/* Generated By:JJTree: Do not edit this line. CPPASTsimple_dtor_declarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTsimple_dtor_declarator extends CPPSimpleNode {
  public CPPASTsimple_dtor_declarator(int id) {
    super(id);
  }

  public CPPASTsimple_dtor_declarator(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8f3767d86a610f8ae45b6990951c42bd (do not edit this line) */
