/* Generated By:JJTree: Do not edit this line. CPPASTenum_specifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTenum_specifier extends CPPSimpleNode {
  public CPPASTenum_specifier(int id) {
    super(id);
  }

  public CPPASTenum_specifier(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2c04bc9925823a14d7b0154041aeb398 (do not edit this line) */
