/* Generated By:JJTree: Do not edit this line. CPPASTinitializer.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTinitializer extends CPPSimpleNode {
  public CPPASTinitializer(int id) {
    super(id);
  }

  public CPPASTinitializer(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0ab431a8f8edca5e18f419d2cb9a99b0 (do not edit this line) */
