/* Generated By:JJTree: Do not edit this line. CPPASTcv_qualifier_seq.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTcv_qualifier_seq extends CPPSimpleNode {
  public CPPASTcv_qualifier_seq(int id) {
    super(id);
  }

  public CPPASTcv_qualifier_seq(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c2e230cc86d3c7929775c3069d81e929 (do not edit this line) */
