/* Generated By:JJTree: Do not edit this line. CPPASTnew_type_id.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTnew_type_id extends CPPSimpleNode {
  public CPPASTnew_type_id(int id) {
    super(id);
  }

  public CPPASTnew_type_id(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=823c5e9ffbda98f550500968ad5a3006 (do not edit this line) */
