/* Generated By:JJTree: Do not edit this line. CPPASTselection_statement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTselection_statement extends CPPSimpleNode {
  public CPPASTselection_statement(int id) {
    super(id);
  }

  public CPPASTselection_statement(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=344ecda3556f8ea4bfd863a81925b6d9 (do not edit this line) */
