/* Generated By:JJTree: Do not edit this line. CPPASTtype_qualifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTtype_qualifier extends CPPSimpleNode {
  public CPPASTtype_qualifier(int id) {
    super(id);
  }

  public CPPASTtype_qualifier(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f388f4e5788f9237faeac0fa349e0f0d (do not edit this line) */
