/* Generated By:JJTree: Do not edit this line. CPPASTassignment_expression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTassignment_expression extends CPPSimpleNode {
  public CPPASTassignment_expression(int id) {
    super(id);
  }

  public CPPASTassignment_expression(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f04fee63d159452f46bfc9e2015e92d9 (do not edit this line) */
