/* Generated By:JJTree: Do not edit this line. CPPASTstatement_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTstatement_list extends CPPSimpleNode {
  public CPPASTstatement_list(int id) {
    super(id);
  }

  public CPPASTstatement_list(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d1c404f00e6f04c47c4242dbd08d9849 (do not edit this line) */
