/* Generated By:JJTree: Do not edit this line. CPPASTinclusive_or_expression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTinclusive_or_expression extends CPPSimpleNode {
  public CPPASTinclusive_or_expression(int id) {
    super(id);
  }

  public CPPASTinclusive_or_expression(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dcf544c0c3613bd13b18fae3f91483bd (do not edit this line) */
