/* Generated By:JJTree: Do not edit this line. CPPASTdtor_definition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTdtor_definition extends CPPSimpleNode {
  public CPPASTdtor_definition(int id) {
    super(id);
  }

  public CPPASTdtor_definition(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cb7ccedcf941dd237c18015a60724137 (do not edit this line) */
