/* Generated By:JJTree: Do not edit this line. CPPASTparameter_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTparameter_list extends CPPSimpleNode {
  public CPPASTparameter_list(int id) {
    super(id);
  }

  public CPPASTparameter_list(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4521831c0f9cab3b7f869a417ec08723 (do not edit this line) */
