/* Generated By:JJTree: Do not edit this line. CPPASTexpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTexpression extends CPPSimpleNode {
  public CPPASTexpression(int id) {
    super(id);
  }

  public CPPASTexpression(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=313d61f06e556a0f08350b55876676a4 (do not edit this line) */
