/* Generated By:JJTree: Do not edit this line. CPPASTdtor_ctor_decl_spec.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTdtor_ctor_decl_spec extends CPPSimpleNode {
  public CPPASTdtor_ctor_decl_spec(int id) {
    super(id);
  }

  public CPPASTdtor_ctor_decl_spec(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cdd598a9570de271a1d471455e4c3021 (do not edit this line) */
