/* Generated By:JJTree: Do not edit this line. CPPASTtemplate_head.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTtemplate_head extends CPPSimpleNode {
  public CPPASTtemplate_head(int id) {
    super(id);
  }

  public CPPASTtemplate_head(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=67a6232069e5df3e3671a8b2145f2d06 (do not edit this line) */
