/* Generated By:JJTree: Do not edit this line. CPPASTinit_declarator_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTinit_declarator_list extends CPPSimpleNode {
  public CPPASTinit_declarator_list(int id) {
    super(id);
  }

  public CPPASTinit_declarator_list(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3376fdcf0907fc780c7a58330348c672 (do not edit this line) */
