/* Generated By:JJTree: Do not edit this line. CPPASTenumerator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTenumerator extends CPPSimpleNode {
  public CPPASTenumerator(int id) {
    super(id);
  }

  public CPPASTenumerator(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e53d018f493752189fcc0f8cf07bbfec (do not edit this line) */
