/* Generated By:JJTree: Do not edit this line. CPPASToptor.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASToptor extends CPPSimpleNode {
  public CPPASToptor(int id) {
    super(id);
  }

  public CPPASToptor(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ff26ea5eb98608c9ee89bd896ff40408 (do not edit this line) */
