/* Generated By:JJTree: Do not edit this line. CPPASTdirect_new_declarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTdirect_new_declarator extends CPPSimpleNode {
  public CPPASTdirect_new_declarator(int id) {
    super(id);
  }

  public CPPASTdirect_new_declarator(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7802f21637690f832f389ff20ae55725 (do not edit this line) */
