/* Generated By:JJTree: Do not edit this line. CPPASTqualified_type.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTqualified_type extends CPPSimpleNode {
  public CPPASTqualified_type(int id) {
    super(id);
  }

  public CPPASTqualified_type(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b53d92195ab98d3dddb25bf5aec5fb9c (do not edit this line) */
