/* Generated By:JJTree: Do not edit this line. CPPASThandler.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASThandler extends CPPSimpleNode {
  public CPPASThandler(int id) {
    super(id);
  }

  public CPPASThandler(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cd55b184d31f424b29f45a54c98c47b4 (do not edit this line) */
