/* Generated By:JJTree: Do not edit this line. CPPASTIncOrDecOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTIncOrDecOperator extends CPPSimpleNode {
  public CPPASTIncOrDecOperator(int id) {
    super(id);
  }

  public CPPASTIncOrDecOperator(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=afc247c95e43a8b9adcd9c8913cbbb0b (do not edit this line) */
