/* Generated By:JJTree: Do not edit this line. CPPASTRoot.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTRoot extends CPPSimpleNode {
  public CPPASTRoot(int id) {
    super(id);
  }

  public CPPASTRoot(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=caca07a969e9db093559206bcb926ab5 (do not edit this line) */
