/* Generated By:JJTree: Do not edit this line. CPPASTclass_head.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTclass_head extends CPPSimpleNode {
  public CPPASTclass_head(int id) {
    super(id);
  }

  public CPPASTclass_head(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7390ab15d19f8869671ff614396e9794 (do not edit this line) */
