/* Generated By:JJTree: Do not edit this line. CPPASTtemplate_parameter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTtemplate_parameter extends CPPSimpleNode {
  public CPPASTtemplate_parameter(int id) {
    super(id);
  }

  public CPPASTtemplate_parameter(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=78a42670a2f33bcb7450bb0414d3c55c (do not edit this line) */
