/* Generated By:JJTree: Do not edit this line. CPPASTpostfix_expression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTpostfix_expression extends CPPSimpleNode {
  public CPPASTpostfix_expression(int id) {
    super(id);
  }

  public CPPASTpostfix_expression(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9d27074a0e4cd83001aee3dac9c7b43f (do not edit this line) */
