/* Generated By:JJTree: Do not edit this line. CPPASTmultiplicative_expression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTmultiplicative_expression extends CPPSimpleNode {
  public CPPASTmultiplicative_expression(int id) {
    super(id);
  }

  public CPPASTmultiplicative_expression(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3a8ffbeb23b04d07a5d182e08efdcdb8 (do not edit this line) */
