/* Generated By:JJTree: Do not edit this line. CPPASTstatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=CPPAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.cpp;

public
class CPPASTstatement extends CPPSimpleNode {
  public CPPASTstatement(int id) {
    super(id);
  }

  public CPPASTstatement(CPPTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=af2c9b346136677004b61128570bb7e5 (do not edit this line) */
