/* Generated By:JavaCC: Do not edit this line. CPPTreeParserTreeConstants.java Version 5.0 */
package com.bupt.cmp.ast.cpp;

public interface CPPTreeParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTVOID = 1;
  public int JJTEXTERNAL_DECLARATION = 2;
  public int JJTFUNCTION_DEFINITION = 3;
  public int JJTFUNC_DECL_DEF = 4;
  public int JJTLINKAGE_SPECIFICATION = 5;
  public int JJTDECLARATIONFORIF = 6;
  public int JJTDECLARATION = 7;
  public int JJTEXTERN_LINKAGE_SPECIFICATION = 8;
  public int JJTTYPE_MODIFIERS = 9;
  public int JJTDECLARATION_SPECIFIERS = 10;
  public int JJTSIMPLE_TYPE_SPECIFIER = 11;
  public int JJTSCOPE_OVERRIDE_LOOKAHEAD = 12;
  public int JJTSCOPE_OVERRIDE = 13;
  public int JJTSCOPE_DECLARATION = 14;
  public int JJTQUALIFIED_ID = 15;
  public int JJTPTR_TO_MEMBER = 16;
  public int JJTQUALIFIED_TYPE = 17;
  public int JJTTYPE_QUALIFIER = 18;
  public int JJTSTORAGE_CLASS_SPECIFIER = 19;
  public int JJTBUILTIN_TYPE_SPECIFIER = 20;
  public int JJTEXTERN_BUILTIN_TYPE_SPECIFIER = 21;
  public int JJTINIT_DECLARATOR_LIST = 22;
  public int JJTINIT_DECLARATOR = 23;
  public int JJTCLASS_HEAD = 24;
  public int JJTCLASS_SPECIFIER = 25;
  public int JJTBASE_CLAUSE = 26;
  public int JJTBASE_SPECIFIER = 27;
  public int JJTACCESS_SPECIFIER = 28;
  public int JJTMEMBER_DECLARATION = 29;
  public int JJTMEMBER_DECLARATOR_LIST = 30;
  public int JJTMEMBER_DECLARATOR = 31;
  public int JJTCONVERSION_FUNCTION_DECL_OR_DEF = 32;
  public int JJTENUM_SPECIFIER = 33;
  public int JJTENUMERATOR_LIST = 34;
  public int JJTENUMERATOR = 35;
  public int JJTPTR_OPERATOR = 36;
  public int JJTCV_QUALIFIER_SEQ = 37;
  public int JJTDECLARATOR = 38;
  public int JJTDIRECT_DECLARATOR = 39;
  public int JJTDECLARATOR_SUFFIXES = 40;
  public int JJTFUNCTION_DECLARATOR_LOOKAHEAD = 41;
  public int JJTFUNCTION_DECLARATOR = 42;
  public int JJTFUNCTION_DIRECT_DECLARATOR = 43;
  public int JJTFUNCTION_DECLARATOR2 = 44;
  public int JJTFUNCTION_DIRECT_DECLARATOR2 = 45;
  public int JJTEXTERN_PARAMETER_LIST = 46;
  public int JJTFUNCTION_INIT = 47;
  public int JJTDTOR_CTOR_DECL_SPEC = 48;
  public int JJTDTOR_DEFINITION = 49;
  public int JJTCTOR_DEFINITION = 50;
  public int JJTCTOR_DECLARATOR_LOOKAHEAD = 51;
  public int JJTCTOR_DECLARATOR = 52;
  public int JJTCTOR_INITIALIZER = 53;
  public int JJTSUPERCLASS_INIT = 54;
  public int JJTDTOR_DECLARATOR = 55;
  public int JJTSIMPLE_DTOR_DECLARATOR = 56;
  public int JJTPARAMETER_LIST = 57;
  public int JJTPARAMETER_DECLARATION_LIST = 58;
  public int JJTPARAMETER_DECLARATION = 59;
  public int JJTINITIALIZER = 60;
  public int JJTTYPE_NAME = 61;
  public int JJTABSTRACT_DECLARATOR = 62;
  public int JJTABSTRACT_DECLARATOR_SUFFIX = 63;
  public int JJTTEMPLATE_HEAD = 64;
  public int JJTTEMPLATE_PARAMETER_LIST = 65;
  public int JJTTEMPLATE_PARAMETER = 66;
  public int JJTTEMPLATE_ID = 67;
  public int JJTTEMPLATE_ARGUMENT_LIST = 68;
  public int JJTTEMPLATE_ARGUMENT = 69;
  public int JJTSTATEMENT_LIST = 70;
  public int JJTSTATEMENT = 71;
  public int JJTLABELED_STATEMENT = 72;
  public int JJTCOMPOUND_STATEMENT = 73;
  public int JJTSELECTION_STATEMENT = 74;
  public int JJTITERATION_STATEMENT = 75;
  public int JJTJUMP_STATEMENT = 76;
  public int JJTTRY_BLOCK = 77;
  public int JJTHANDLER = 78;
  public int JJTEXCEPTION_DECLARATION = 79;
  public int JJTTHROW_STATEMENT = 80;
  public int JJTEXPRESSION = 81;
  public int JJTASSIGNMENT_EXPRESSION = 82;
  public int JJTCONDITIONAL_EXPRESSION = 83;
  public int JJTCONSTANT_EXPRESSION = 84;
  public int JJTLOGICAL_OR_EXPRESSION = 85;
  public int JJTLOGICAL_AND_EXPRESSION = 86;
  public int JJTINCLUSIVE_OR_EXPRESSION = 87;
  public int JJTEXCLUSIVE_OR_EXPRESSION = 88;
  public int JJTAND_EXPRESSION = 89;
  public int JJTEQUALITY_EXPRESSION = 90;
  public int JJTRELATIONAL_EXPRESSION = 91;
  public int JJTSHIFT_EXPRESSION = 92;
  public int JJTADDITIVE_EXPRESSION = 93;
  public int JJTMULTIPLICATIVE_EXPRESSION = 94;
  public int JJTPM_EXPRESSION = 95;
  public int JJTCAST_EXPRESSION = 96;
  public int JJTINCORDECOPERATOR = 97;
  public int JJTSIZEOFOPERATOR = 98;
  public int JJTUNARY_EXPRESSION = 99;
  public int JJTNEW_EXPRESSION = 100;
  public int JJTNEW_TYPE_ID = 101;
  public int JJTNEW_DECLARATOR = 102;
  public int JJTDIRECT_NEW_DECLARATOR = 103;
  public int JJTNEW_INITIALIZER = 104;
  public int JJTDELETE_EXPRESSION = 105;
  public int JJTUNARY_OPERATOR = 106;
  public int JJTPOSTFIX_EXPRESSION = 107;
  public int JJTID_EXPRESSION = 108;
  public int JJTPRIMARY_EXPRESSION = 109;
  public int JJTEXPRESSION_LIST = 110;
  public int JJTCONSTANT = 111;
  public int JJTOPTOR = 112;
  public int JJTEXCEPTION_SPEC = 113;
  public int JJTEXCEPTION_LIST = 114;


  public String[] jjtNodeName = {
    "Root",
    "void",
    "external_declaration",
    "function_definition",
    "func_decl_def",
    "linkage_specification",
    "declarationforif",
    "declaration",
    "extern_linkage_specification",
    "type_modifiers",
    "declaration_specifiers",
    "simple_type_specifier",
    "scope_override_lookahead",
    "scope_override",
    "Scope_declaration",
    "qualified_id",
    "ptr_to_member",
    "qualified_type",
    "type_qualifier",
    "storage_class_specifier",
    "builtin_type_specifier",
    "extern_builtin_type_specifier",
    "init_declarator_list",
    "init_declarator",
    "class_head",
    "class_specifier",
    "base_clause",
    "base_specifier",
    "access_specifier",
    "member_declaration",
    "member_declarator_list",
    "member_declarator",
    "conversion_function_decl_or_def",
    "enum_specifier",
    "enumerator_list",
    "enumerator",
    "ptr_operator",
    "cv_qualifier_seq",
    "declarator",
    "direct_declarator",
    "declarator_suffixes",
    "function_declarator_lookahead",
    "function_declarator",
    "function_direct_declarator",
    "function_declarator2",
    "function_direct_declarator2",
    "extern_parameter_list",
    "function_init",
    "dtor_ctor_decl_spec",
    "dtor_definition",
    "ctor_definition",
    "ctor_declarator_lookahead",
    "ctor_declarator",
    "ctor_initializer",
    "superclass_init",
    "dtor_declarator",
    "simple_dtor_declarator",
    "parameter_list",
    "parameter_declaration_list",
    "parameter_declaration",
    "initializer",
    "type_name",
    "abstract_declarator",
    "abstract_declarator_suffix",
    "template_head",
    "template_parameter_list",
    "template_parameter",
    "template_id",
    "template_argument_list",
    "template_argument",
    "statement_list",
    "statement",
    "labeled_statement",
    "compound_statement",
    "selection_statement",
    "iteration_statement",
    "jump_statement",
    "try_block",
    "handler",
    "exception_declaration",
    "throw_statement",
    "expression",
    "assignment_expression",
    "conditional_expression",
    "constant_expression",
    "logical_or_expression",
    "logical_and_expression",
    "inclusive_or_expression",
    "exclusive_or_expression",
    "and_expression",
    "equality_expression",
    "relational_expression",
    "shift_expression",
    "additive_expression",
    "multiplicative_expression",
    "pm_expression",
    "cast_expression",
    "IncOrDecOperator",
    "SizeOfOperator",
    "unary_expression",
    "new_expression",
    "new_type_id",
    "new_declarator",
    "direct_new_declarator",
    "new_initializer",
    "delete_expression",
    "unary_operator",
    "postfix_expression",
    "id_expression",
    "primary_expression",
    "expression_list",
    "constant",
    "optor",
    "exception_spec",
    "exception_list",
  };
}
/* JavaCC - OriginalChecksum=d30affd5c8ff9c40896336f5d9eb3a67 (do not edit this line) */
