/* Generated By:JJTree&JavaCC: Do not edit this line. CPPTreeParserConstants.java */
package com.bupt.cmp.ast.cpp;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CPPTreeParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int __TRY = 1;
  /** RegularExpression Id. */
  int __ASM = 2;
  /** RegularExpression Id. */
  int __EXCEPT = 3;
  /** RegularExpression Id. */
  int __FINALLY = 4;
  /** RegularExpression Id. */
  int __LEAVE = 5;
  /** RegularExpression Id. */
  int LCURLYBRACE = 25;
  /** RegularExpression Id. */
  int RCURLYBRACE = 26;
  /** RegularExpression Id. */
  int LSQUAREBRACKET = 27;
  /** RegularExpression Id. */
  int RSQUAREBRACKET = 28;
  /** RegularExpression Id. */
  int LPARENTHESIS = 29;
  /** RegularExpression Id. */
  int RPARENTHESIS = 30;
  /** RegularExpression Id. */
  int SCOPE = 31;
  /** RegularExpression Id. */
  int COLON = 32;
  /** RegularExpression Id. */
  int SEMICOLON = 33;
  /** RegularExpression Id. */
  int COMMA = 34;
  /** RegularExpression Id. */
  int QUESTIONMARK = 35;
  /** RegularExpression Id. */
  int ELLIPSIS = 36;
  /** RegularExpression Id. */
  int ASSIGNEQUAL = 37;
  /** RegularExpression Id. */
  int TIMESEQUAL = 38;
  /** RegularExpression Id. */
  int DIVIDEEQUAL = 39;
  /** RegularExpression Id. */
  int MODEQUAL = 40;
  /** RegularExpression Id. */
  int PLUSEQUAL = 41;
  /** RegularExpression Id. */
  int MINUSEQUAL = 42;
  /** RegularExpression Id. */
  int SHIFTLEFTEQUAL = 43;
  /** RegularExpression Id. */
  int SHIFTRIGHTEQUAL = 44;
  /** RegularExpression Id. */
  int BITWISEANDEQUAL = 45;
  /** RegularExpression Id. */
  int BITWISEXOREQUAL = 46;
  /** RegularExpression Id. */
  int BITWISEOREQUAL = 47;
  /** RegularExpression Id. */
  int OR_OP = 48;
  /** RegularExpression Id. */
  int AND_OP = 49;
  /** RegularExpression Id. */
  int BITWISEOR = 50;
  /** RegularExpression Id. */
  int BITWISEXOR = 51;
  /** RegularExpression Id. */
  int AMPERSAND = 52;
  /** RegularExpression Id. */
  int EQUAL = 53;
  /** RegularExpression Id. */
  int NOTEQUAL = 54;
  /** RegularExpression Id. */
  int LESSTHAN = 55;
  /** RegularExpression Id. */
  int GREATERTHAN = 56;
  /** RegularExpression Id. */
  int LESSTHANOREQUALTO = 57;
  /** RegularExpression Id. */
  int GREATERTHANOREQUALTO = 58;
  /** RegularExpression Id. */
  int SHIFTLEFT = 59;
  /** RegularExpression Id. */
  int SHIFTRIGHT = 60;
  /** RegularExpression Id. */
  int PLUS = 61;
  /** RegularExpression Id. */
  int MINUS = 62;
  /** RegularExpression Id. */
  int STAR = 63;
  /** RegularExpression Id. */
  int DIVIDE = 64;
  /** RegularExpression Id. */
  int MOD = 65;
  /** RegularExpression Id. */
  int PLUSPLUS = 66;
  /** RegularExpression Id. */
  int MINUSMINUS = 67;
  /** RegularExpression Id. */
  int TILDE = 68;
  /** RegularExpression Id. */
  int NOT_OP = 69;
  /** RegularExpression Id. */
  int DOT = 70;
  /** RegularExpression Id. */
  int POINTERTO = 71;
  /** RegularExpression Id. */
  int DOTSTAR = 72;
  /** RegularExpression Id. */
  int ARROWSTAR = 73;
  /** RegularExpression Id. */
  int AND = 74;
  /** RegularExpression Id. */
  int AND_EQ = 75;
  /** RegularExpression Id. */
  int ASM = 76;
  /** RegularExpression Id. */
  int AUTO = 77;
  /** RegularExpression Id. */
  int BITAND = 78;
  /** RegularExpression Id. */
  int BITOR = 79;
  /** RegularExpression Id. */
  int BOOL = 80;
  /** RegularExpression Id. */
  int BREAK = 81;
  /** RegularExpression Id. */
  int CASE = 82;
  /** RegularExpression Id. */
  int CATCH = 83;
  /** RegularExpression Id. */
  int CHAR = 84;
  /** RegularExpression Id. */
  int CLASS = 85;
  /** RegularExpression Id. */
  int COMPL = 86;
  /** RegularExpression Id. */
  int CONST = 87;
  /** RegularExpression Id. */
  int CONST_CAST = 88;
  /** RegularExpression Id. */
  int CONTINUE = 89;
  /** RegularExpression Id. */
  int _DEFAULT = 90;
  /** RegularExpression Id. */
  int DELETE = 91;
  /** RegularExpression Id. */
  int DO = 92;
  /** RegularExpression Id. */
  int DOUBLE = 93;
  /** RegularExpression Id. */
  int DYNAMIC_CAST = 94;
  /** RegularExpression Id. */
  int ELSE = 95;
  /** RegularExpression Id. */
  int ENUM = 96;
  /** RegularExpression Id. */
  int EXPLICIT = 97;
  /** RegularExpression Id. */
  int EXPORT = 98;
  /** RegularExpression Id. */
  int EXTERN = 99;
  /** RegularExpression Id. */
  int FALSE = 100;
  /** RegularExpression Id. */
  int FLOAT = 101;
  /** RegularExpression Id. */
  int FOR = 102;
  /** RegularExpression Id. */
  int FRIEND = 103;
  /** RegularExpression Id. */
  int GOTO = 104;
  /** RegularExpression Id. */
  int IF = 105;
  /** RegularExpression Id. */
  int INLINE = 106;
  /** RegularExpression Id. */
  int INT = 107;
  /** RegularExpression Id. */
  int LONG = 108;
  /** RegularExpression Id. */
  int mutable = 109;
  /** RegularExpression Id. */
  int NAMESPACE = 110;
  /** RegularExpression Id. */
  int NEW = 111;
  /** RegularExpression Id. */
  int NOT = 112;
  /** RegularExpression Id. */
  int NOT_EQ = 113;
  /** RegularExpression Id. */
  int OPERATOR = 114;
  /** RegularExpression Id. */
  int OR = 115;
  /** RegularExpression Id. */
  int OR_EQ = 116;
  /** RegularExpression Id. */
  int PRIVATE = 117;
  /** RegularExpression Id. */
  int PROTECTED = 118;
  /** RegularExpression Id. */
  int PUBLIC = 119;
  /** RegularExpression Id. */
  int REGISTER = 120;
  /** RegularExpression Id. */
  int REINTERPRET = 121;
  /** RegularExpression Id. */
  int RETURN = 122;
  /** RegularExpression Id. */
  int SHORT = 123;
  /** RegularExpression Id. */
  int SIGNED = 124;
  /** RegularExpression Id. */
  int SIZEOF = 125;
  /** RegularExpression Id. */
  int _STATIC = 126;
  /** RegularExpression Id. */
  int STATIC_CAST = 127;
  /** RegularExpression Id. */
  int STRUCT = 128;
  /** RegularExpression Id. */
  int SWITCH = 129;
  /** RegularExpression Id. */
  int TEMPLATE = 130;
  /** RegularExpression Id. */
  int THIS = 131;
  /** RegularExpression Id. */
  int THROW = 132;
  /** RegularExpression Id. */
  int TRUE = 133;
  /** RegularExpression Id. */
  int TRY = 134;
  /** RegularExpression Id. */
  int TYPEDEF = 135;
  /** RegularExpression Id. */
  int TYPEID = 136;
  /** RegularExpression Id. */
  int TYPENAME = 137;
  /** RegularExpression Id. */
  int UNION = 138;
  /** RegularExpression Id. */
  int UNSIGNED = 139;
  /** RegularExpression Id. */
  int USING = 140;
  /** RegularExpression Id. */
  int VIRTUAL = 141;
  /** RegularExpression Id. */
  int VOID = 142;
  /** RegularExpression Id. */
  int VOLATILE = 143;
  /** RegularExpression Id. */
  int WCHAR_T = 144;
  /** RegularExpression Id. */
  int DWORD = 145;
  /** RegularExpression Id. */
  int WORD = 146;
  /** RegularExpression Id. */
  int BYTE = 147;
  /** RegularExpression Id. */
  int WHILE = 148;
  /** RegularExpression Id. */
  int XOR = 149;
  /** RegularExpression Id. */
  int XOR_EQ = 150;
  /** RegularExpression Id. */
  int STD = 151;
  /** RegularExpression Id. */
  int OCTALINT = 152;
  /** RegularExpression Id. */
  int OCTALLONG = 153;
  /** RegularExpression Id. */
  int UNSIGNED_OCTALINT = 154;
  /** RegularExpression Id. */
  int UNSIGNED_OCTALLONG = 155;
  /** RegularExpression Id. */
  int DECIMALINT = 156;
  /** RegularExpression Id. */
  int DECIMALLONG = 157;
  /** RegularExpression Id. */
  int UNSIGNED_DECIMALINT = 158;
  /** RegularExpression Id. */
  int UNSIGNED_DECIMALLONG = 159;
  /** RegularExpression Id. */
  int HEXADECIMALINT = 160;
  /** RegularExpression Id. */
  int HEXADECIMALLONG = 161;
  /** RegularExpression Id. */
  int UNSIGNED_HEXADECIMALINT = 162;
  /** RegularExpression Id. */
  int UNSIGNED_HEXADECIMALLONG = 163;
  /** RegularExpression Id. */
  int FLOATONE = 164;
  /** RegularExpression Id. */
  int FLOATTWO = 165;
  /** RegularExpression Id. */
  int CHARACTER = 166;
  /** RegularExpression Id. */
  int STRING = 167;
  /** RegularExpression Id. */
  int ID = 168;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_COMMENT = 2;
  /** Lexical state. */
  int ELSE_STATEMENT = 3;
  /** Lexical state. */
  int PREPROCESSOR_OUTPUT = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"__try\"",
    "\"__asm\"",
    "\"__except\"",
    "\"__finally\"",
    "\"__leave\"",
    "\" \"",
    "\"\\t\"",
    "\"\\r\\n\"",
    "\"\\n\"",
    "\"//\"",
    "\"#ifdef\"",
    "\"/*\"",
    "\"#else\"",
    "\"#\"",
    "\"\\n\"",
    "<token of kind 16>",
    "\"*/\"",
    "<token of kind 18>",
    "\"#endif\"",
    "<token of kind 20>",
    "\"\\n\"",
    "\"\\\\\\n\"",
    "\"\\\\\\r\\n\"",
    "<token of kind 24>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "<SCOPE>",
    "\":\"",
    "\";\"",
    "\",\"",
    "\"?\"",
    "\"...\"",
    "\"=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"+=\"",
    "\"-=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"&=\"",
    "\"^=\"",
    "\"|=\"",
    "\"||\"",
    "\"&&\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"<<\"",
    "\">>\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"++\"",
    "\"--\"",
    "\"~\"",
    "\"!\"",
    "\".\"",
    "\"->\"",
    "\".*\"",
    "\"->*\"",
    "\"and\"",
    "\"and_eq\"",
    "\"asm\"",
    "\"auto\"",
    "\"bitand\"",
    "\"bitor\"",
    "\"bool\"",
    "\"break\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"compl\"",
    "\"const\"",
    "\"const_cast\"",
    "\"continue\"",
    "\"default\"",
    "\"delete\"",
    "\"do\"",
    "\"double\"",
    "\"dynamic_cast\"",
    "\"else\"",
    "\"enum\"",
    "\"explicit\"",
    "\"export\"",
    "\"extern\"",
    "\"false\"",
    "\"float\"",
    "\"for\"",
    "\"friend\"",
    "\"goto\"",
    "\"if\"",
    "\"inline\"",
    "\"int\"",
    "\"long\"",
    "\"mutable\"",
    "\"namespace\"",
    "\"new\"",
    "\"not\"",
    "\"not_eq\"",
    "\"operator\"",
    "\"or \"",
    "\"or_eq \"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"register\"",
    "\"reinterpret_cast\"",
    "\"return\"",
    "\"short\"",
    "\"signed\"",
    "\"sizeof\"",
    "\"static\"",
    "\"static_cast\"",
    "\"struct\"",
    "\"switch\"",
    "\"template\"",
    "\"this\"",
    "\"throw\"",
    "\"true \"",
    "<TRY>",
    "\"typedef\"",
    "\"typeid\"",
    "\"typename\"",
    "\"union\"",
    "\"unsigned\"",
    "\"using\"",
    "\"virtual\"",
    "\"void\"",
    "\"volatile\"",
    "\"wchar_t\"",
    "\"DWORD\"",
    "\"WORD\"",
    "\"BYTE\"",
    "\"while\"",
    "\"xor\"",
    "\"xor_eq \"",
    "\"std\"",
    "<OCTALINT>",
    "<OCTALLONG>",
    "<UNSIGNED_OCTALINT>",
    "<UNSIGNED_OCTALLONG>",
    "<DECIMALINT>",
    "<DECIMALLONG>",
    "<UNSIGNED_DECIMALINT>",
    "<UNSIGNED_DECIMALLONG>",
    "<HEXADECIMALINT>",
    "<HEXADECIMALLONG>",
    "<UNSIGNED_HEXADECIMALINT>",
    "<UNSIGNED_HEXADECIMALLONG>",
    "<FLOATONE>",
    "<FLOATTWO>",
    "<CHARACTER>",
    "<STRING>",
    "<ID>",
    "\"finally\"",
    "\"::\"",
    "\"true\"",
  };

}
