/* Generated By:JJTree: Do not edit this line. JavaASTResultType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTResultType extends JavaSimpleNode {
  public JavaASTResultType(int id) {
    super(id);
  }

  public JavaASTResultType(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=14b65065bb87a2dcaea947434907359c (do not edit this line) */
