/* Generated By:JJTree: Do not edit this line. JavaASTAllocationExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTAllocationExpression extends JavaSimpleNode {
  public JavaASTAllocationExpression(int id) {
    super(id);
  }

  public JavaASTAllocationExpression(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3c0d1e3dcd357ed3d35003c603040ad6 (do not edit this line) */
