/* Generated By:JJTree: Do not edit this line. JavaASTRelationalExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTRelationalExpression extends JavaSimpleNode {
  public JavaASTRelationalExpression(int id) {
    super(id);
  }

  public JavaASTRelationalExpression(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e2fe240f85511195903ac62d49e60be8 (do not edit this line) */
