/* Generated By:JJTree: Do not edit this line. JavaASTTryStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTTryStatement extends JavaSimpleNode {
  public JavaASTTryStatement(int id) {
    super(id);
  }

  public JavaASTTryStatement(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=37663ab473078f02e54f29b9dea47c68 (do not edit this line) */
