/* Generated By:JJTree: Do not edit this line. JavaASTIfStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTIfStatement extends JavaSimpleNode {
  public JavaASTIfStatement(int id) {
    super(id);
  }

  public JavaASTIfStatement(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=57bef8efd538af24996f97942a57f6ff (do not edit this line) */
