/* Generated By:JJTree: Do not edit this line. JavaASTWhileStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTWhileStatement extends JavaSimpleNode {
  public JavaASTWhileStatement(int id) {
    super(id);
  }

  public JavaASTWhileStatement(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c2e8ec7e5129ee0639286e0ab13b12dd (do not edit this line) */
