/* Generated By:JJTree: Do not edit this line. JavaASTVariableDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTVariableDeclarator extends JavaSimpleNode {
  public JavaASTVariableDeclarator(int id) {
    super(id);
  }

  public JavaASTVariableDeclarator(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a16b15d8699243569e18d577eda2d42f (do not edit this line) */
