/* Generated By:JJTree: Do not edit this line. JavaASTConditionalAndExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTConditionalAndExpression extends JavaSimpleNode {
  public JavaASTConditionalAndExpression(int id) {
    super(id);
  }

  public JavaASTConditionalAndExpression(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=67d2f690d5e2027ef091749d91a92530 (do not edit this line) */
