/* Generated By:JJTree: Do not edit this line. JavaASTTypeBound.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTTypeBound extends JavaSimpleNode {
  public JavaASTTypeBound(int id) {
    super(id);
  }

  public JavaASTTypeBound(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7caca13269b9f3233a146609105c2f7d (do not edit this line) */
