/* Generated By:JJTree: Do not edit this line. JavaASTBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTBlock extends JavaSimpleNode {
  public JavaASTBlock(int id) {
    super(id);
  }

  public JavaASTBlock(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0acd65f8cf8b57676fed6e380484f70a (do not edit this line) */
