/* Generated By:JJTree: Do not edit this line. JavaASTReturnStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTReturnStatement extends JavaSimpleNode {
  public JavaASTReturnStatement(int id) {
    super(id);
  }

  public JavaASTReturnStatement(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5d7f3a28a6993c0e5951f7706494c823 (do not edit this line) */
