/* Generated By:JJTree: Do not edit this line. JavaASTPrimaryExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTPrimaryExpression extends JavaSimpleNode {
  public JavaASTPrimaryExpression(int id) {
    super(id);
  }

  public JavaASTPrimaryExpression(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=167fb4c51c712f9dd7fe1a7266917762 (do not edit this line) */
