/* Generated By:JJTree: Do not edit this line. JavaASTContinueStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTContinueStatement extends JavaSimpleNode {
  public JavaASTContinueStatement(int id) {
    super(id);
  }

  public JavaASTContinueStatement(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5bd865307381df03ea64ae271f70afb4 (do not edit this line) */
