/* Generated By:JJTree: Do not edit this line. JavaASTArguments.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTArguments extends JavaSimpleNode {
  public JavaASTArguments(int id) {
    super(id);
  }

  public JavaASTArguments(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d556749c3b47b58a11b99c8b12089034 (do not edit this line) */
