/* Generated By:JJTree: Do not edit this line. JavaASTBreakStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTBreakStatement extends JavaSimpleNode {
  public JavaASTBreakStatement(int id) {
    super(id);
  }

  public JavaASTBreakStatement(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e658c98ebac075f58b9b616f84cf0bb7 (do not edit this line) */
