/* Generated By:JJTree: Do not edit this line. JavaASTAnnotationTypeDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTAnnotationTypeDeclaration extends JavaSimpleNode {
  public JavaASTAnnotationTypeDeclaration(int id) {
    super(id);
  }

  public JavaASTAnnotationTypeDeclaration(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fc00a0cd3fd4d33a0c804bad8044351e (do not edit this line) */
