/* Generated By:JJTree: Do not edit this line. JavaASTUnaryOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTUnaryOperator extends JavaSimpleNode {
  public JavaASTUnaryOperator(int id) {
    super(id);
  }

  public JavaASTUnaryOperator(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=14d08cec17c862c0ef04bae7cd23e258 (do not edit this line) */
