/* Generated By:JJTree: Do not edit this line. JavaASTTypeParameters.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTTypeParameters extends JavaSimpleNode {
  public JavaASTTypeParameters(int id) {
    super(id);
  }

  public JavaASTTypeParameters(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=94860fe2299d85689f2d86d67e5acb41 (do not edit this line) */
