/* Generated By:JJTree: Do not edit this line. JavaASTEnumBody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTEnumBody extends JavaSimpleNode {
  public JavaASTEnumBody(int id) {
    super(id);
  }

  public JavaASTEnumBody(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2c478db8c4369441ea13bc1c8e30a5aa (do not edit this line) */
