/* Generated By:JJTree: Do not edit this line. JavaASTConstructorDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTConstructorDeclaration extends JavaSimpleNode {
  public JavaASTConstructorDeclaration(int id) {
    super(id);
  }

  public JavaASTConstructorDeclaration(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ca80d0fed43fec38e950d13761220cc4 (do not edit this line) */
