/* Generated By:JJTree: Do not edit this line. JavaASTRUNSIGNEDSHIFT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTRUNSIGNEDSHIFT extends JavaSimpleNode {
  public JavaASTRUNSIGNEDSHIFT(int id) {
    super(id);
  }

  public JavaASTRUNSIGNEDSHIFT(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1f0583c9b5ced09348049f360ae86bca (do not edit this line) */
