/* Generated By:JJTree: Do not edit this line. JavaASTUnaryOperatorNotPlusMinus.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTUnaryOperatorNotPlusMinus extends JavaSimpleNode {
  public JavaASTUnaryOperatorNotPlusMinus(int id) {
    super(id);
  }

  public JavaASTUnaryOperatorNotPlusMinus(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f1e23e4176c4f54ea6681fbcdae76478 (do not edit this line) */
