/* Generated By:JJTree: Do not edit this line. JavaASTFieldDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTFieldDeclaration extends JavaSimpleNode {
  public JavaASTFieldDeclaration(int id) {
    super(id);
  }

  public JavaASTFieldDeclaration(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=efbcb81167e932fe223ca8023331dd28 (do not edit this line) */
