/* Generated By:JJTree: Do not edit this line. JavaASTLocalVariableDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTLocalVariableDeclaration extends JavaSimpleNode {
  public JavaASTLocalVariableDeclaration(int id) {
    super(id);
  }

  public JavaASTLocalVariableDeclaration(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=71522f62e26c00e389c310ca15503a67 (do not edit this line) */
