/* Generated By:JJTree: Do not edit this line. JavaASTClassOrInterfaceBodyDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTClassOrInterfaceBodyDeclaration extends JavaSimpleNode {
  public JavaASTClassOrInterfaceBodyDeclaration(int id) {
    super(id);
  }

  public JavaASTClassOrInterfaceBodyDeclaration(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cdaa173cfdd8314df9f252199ba6dec3 (do not edit this line) */
