/* Generated By:JJTree: Do not edit this line. JavaASTMultiplicativeExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTMultiplicativeExpression extends JavaSimpleNode {
  public JavaASTMultiplicativeExpression(int id) {
    super(id);
  }

  public JavaASTMultiplicativeExpression(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=627e24f3a9cba9dd5e164ebc4997e49d (do not edit this line) */
