/* Generated By:JJTree: Do not edit this line. JavaASTMethodDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTMethodDeclaration extends JavaSimpleNode {
  public JavaASTMethodDeclaration(int id) {
    super(id);
  }

  public JavaASTMethodDeclaration(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c22214723c12f9121bd9df9b5697ac39 (do not edit this line) */
