/* Generated By:JJTree: Do not edit this line. JavaASTAnnotation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTAnnotation extends JavaSimpleNode {
  public JavaASTAnnotation(int id) {
    super(id);
  }

  public JavaASTAnnotation(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d3af6d4c78229c70eeb6ca70d312aad7 (do not edit this line) */
