/* Generated By:JJTree: Do not edit this line. JavaASTCastExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTCastExpression extends JavaSimpleNode {
  public JavaASTCastExpression(int id) {
    super(id);
  }

  public JavaASTCastExpression(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4c67550f30728835306a83d800fef9cc (do not edit this line) */
