/* Generated By:JJTree: Do not edit this line. JavaASTAnnotationTypeMemberDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTAnnotationTypeMemberDeclaration extends JavaSimpleNode {
  public JavaASTAnnotationTypeMemberDeclaration(int id) {
    super(id);
  }

  public JavaASTAnnotationTypeMemberDeclaration(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0e05085f86d8e9c71a4507c4441dcb05 (do not edit this line) */
