/* Generated By:JJTree: Do not edit this line. JavaASTBlockStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTBlockStatement extends JavaSimpleNode {
  public JavaASTBlockStatement(int id) {
    super(id);
  }

  public JavaASTBlockStatement(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9a337e71371de82b61c8c1c8a2bc82cd (do not edit this line) */
