/* Generated By:JJTree: Do not edit this line. JavaASTFormalParameters.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTFormalParameters extends JavaSimpleNode {
  public JavaASTFormalParameters(int id) {
    super(id);
  }

  public JavaASTFormalParameters(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=398d2a867b0d15928d98fbd2cbdd5207 (do not edit this line) */
