/* Generated By:JJTree: Do not edit this line. JavaASTConditionalExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTConditionalExpression extends JavaSimpleNode {
  public JavaASTConditionalExpression(int id) {
    super(id);
  }

  public JavaASTConditionalExpression(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e8eac61c7e1804687ca2f38242579015 (do not edit this line) */
