/* Generated By:JJTree: Do not edit this line. JavaASTName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTName extends JavaSimpleNode {
  public JavaASTName(int id) {
    super(id);
  }

  public JavaASTName(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=08d4142bd15231e8221420c6714edc02 (do not edit this line) */
