/* Generated By:JJTree: Do not edit this line. JavaASTIncOrDecOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTIncOrDecOperator extends JavaSimpleNode {
  public JavaASTIncOrDecOperator(int id) {
    super(id);
  }

  public JavaASTIncOrDecOperator(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=62a7f37397cb5f8ad7e8b671a600e6ec (do not edit this line) */
