/* Generated By:JJTree: Do not edit this line. JavaASTNullLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTNullLiteral extends JavaSimpleNode {
  public JavaASTNullLiteral(int id) {
    super(id);
  }

  public JavaASTNullLiteral(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=954f75bb46ccfe06f8ac9a81464b4cb5 (do not edit this line) */
