/* Generated By:JJTree: Do not edit this line. JavaASTArgumentList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTArgumentList extends JavaSimpleNode {
  public JavaASTArgumentList(int id) {
    super(id);
  }

  public JavaASTArgumentList(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e48d81bf760e8d07d8d4ae08043caf28 (do not edit this line) */
