/* Generated By:JJTree: Do not edit this line. JavaASTAnnotationTypeBody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTAnnotationTypeBody extends JavaSimpleNode {
  public JavaASTAnnotationTypeBody(int id) {
    super(id);
  }

  public JavaASTAnnotationTypeBody(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9525b318703efecb2f7e46717134aa5f (do not edit this line) */
