/* Generated By:JJTree: Do not edit this line. JavaASTInclusiveOrExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTInclusiveOrExpression extends JavaSimpleNode {
  public JavaASTInclusiveOrExpression(int id) {
    super(id);
  }

  public JavaASTInclusiveOrExpression(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4869ca34881293fb2bf25afef638a96d (do not edit this line) */
