/* Generated By:JJTree: Do not edit this line. JavaASTEnumDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTEnumDeclaration extends JavaSimpleNode {
  public JavaASTEnumDeclaration(int id) {
    super(id);
  }

  public JavaASTEnumDeclaration(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d6c4913746628b224106535d7837b710 (do not edit this line) */
