/* Generated By:JJTree: Do not edit this line. JavaASTSingleMemberAnnotation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTSingleMemberAnnotation extends JavaSimpleNode {
  public JavaASTSingleMemberAnnotation(int id) {
    super(id);
  }

  public JavaASTSingleMemberAnnotation(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=02ef01e8ef241c3a075f4a965ecb401d (do not edit this line) */
