/* Generated By:JJTree: Do not edit this line. JavaASTForInit.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTForInit extends JavaSimpleNode {
  public JavaASTForInit(int id) {
    super(id);
  }

  public JavaASTForInit(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b3e01a6f87bc520498ea5e4a0187ebe0 (do not edit this line) */
