/* Generated By:JJTree: Do not edit this line. JavaASTMethodDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTMethodDeclarator extends JavaSimpleNode {
  public JavaASTMethodDeclarator(int id) {
    super(id);
  }

  public JavaASTMethodDeclarator(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=13c31639573342d9fa1c28a63fe37232 (do not edit this line) */
