/* Generated By:JJTree: Do not edit this line. JavaASTExclusiveOrExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTExclusiveOrExpression extends JavaSimpleNode {
  public JavaASTExclusiveOrExpression(int id) {
    super(id);
  }

  public JavaASTExclusiveOrExpression(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c5fa09311162c8df9f9e93df6de53da6 (do not edit this line) */
