/* Generated By:JJTree: Do not edit this line. JavaASTInitializer.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTInitializer extends JavaSimpleNode {
  public JavaASTInitializer(int id) {
    super(id);
  }

  public JavaASTInitializer(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e94aa21454d3c5c80e033ec7eeffdd21 (do not edit this line) */
