/* Generated By:JJTree: Do not edit this line. JavaASTForStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTForStatement extends JavaSimpleNode {
  public JavaASTForStatement(int id) {
    super(id);
  }

  public JavaASTForStatement(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fabd17c9ca062d59269f23f601303acb (do not edit this line) */
