/* Generated By:JJTree: Do not edit this line. JavaASTShiftExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTShiftExpression extends JavaSimpleNode {
  public JavaASTShiftExpression(int id) {
    super(id);
  }

  public JavaASTShiftExpression(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a328c5758d4dbbe4084bd0ccb98b5593 (do not edit this line) */
