/* Generated By:JJTree: Do not edit this line. JavaASTMemberValueArrayInitializer.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTMemberValueArrayInitializer extends JavaSimpleNode {
  public JavaASTMemberValueArrayInitializer(int id) {
    super(id);
  }

  public JavaASTMemberValueArrayInitializer(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c955824de74e30ddb89480e05a08ac4a (do not edit this line) */
