/* Generated By:JJTree: Do not edit this line. JavaASTTypeParameter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTTypeParameter extends JavaSimpleNode {
  public JavaASTTypeParameter(int id) {
    super(id);
  }

  public JavaASTTypeParameter(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e09f7ad09a2d314146adddadf0af6477 (do not edit this line) */
