/* Generated By:JJTree: Do not edit this line. JavaASTSwitchStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTSwitchStatement extends JavaSimpleNode {
  public JavaASTSwitchStatement(int id) {
    super(id);
  }

  public JavaASTSwitchStatement(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=75ca71875288528b22eef751fd2d62bf (do not edit this line) */
