/* Generated By:JJTree: Do not edit this line. JavaASTAssertStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTAssertStatement extends JavaSimpleNode {
  public JavaASTAssertStatement(int id) {
    super(id);
  }

  public JavaASTAssertStatement(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d7dd35f31c6d6099c412a9a738039cda (do not edit this line) */
