/* Generated By:JJTree: Do not edit this line. JavaASTStatementExpressionList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTStatementExpressionList extends JavaSimpleNode {
  public JavaASTStatementExpressionList(int id) {
    super(id);
  }

  public JavaASTStatementExpressionList(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9cbf25b11883513a6ef997a0c8dd4771 (do not edit this line) */
