/* Generated By:JJTree: Do not edit this line. JavaASTPackageDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTPackageDeclaration extends JavaSimpleNode {
  public JavaASTPackageDeclaration(int id) {
    super(id);
  }

  public JavaASTPackageDeclaration(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7e9a0c7abe9e0803bdd7d0e951538b47 (do not edit this line) */
