/* Generated By:JJTree: Do not edit this line. JavaASTPrimaryPrefix.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTPrimaryPrefix extends JavaSimpleNode {
  public JavaASTPrimaryPrefix(int id) {
    super(id);
  }

  public JavaASTPrimaryPrefix(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ac2e49bbfa270d539d5eb812aaa45209 (do not edit this line) */
