/* Generated By:JJTree: Do not edit this line. JavaASTVariableInitializer.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTVariableInitializer extends JavaSimpleNode {
  public JavaASTVariableInitializer(int id) {
    super(id);
  }

  public JavaASTVariableInitializer(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5f13c867d1247f7ab32968bd716e4ade (do not edit this line) */
