/* Generated By:JJTree: Do not edit this line. JavaASTExplicitConstructorInvocation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTExplicitConstructorInvocation extends JavaSimpleNode {
  public JavaASTExplicitConstructorInvocation(int id) {
    super(id);
  }

  public JavaASTExplicitConstructorInvocation(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=81a002d5f456b5d4a368d909a5563aee (do not edit this line) */
