/* Generated By:JJTree: Do not edit this line. JavaASTMemberSelector.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTMemberSelector extends JavaSimpleNode {
  public JavaASTMemberSelector(int id) {
    super(id);
  }

  public JavaASTMemberSelector(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4deef38800b006502f2235da0ee27a0f (do not edit this line) */
