/* Generated By:JJTree: Do not edit this line. JavaASTMarkerAnnotation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTMarkerAnnotation extends JavaSimpleNode {
  public JavaASTMarkerAnnotation(int id) {
    super(id);
  }

  public JavaASTMarkerAnnotation(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0c0dc15d6d3e1201d1cbd1d351158575 (do not edit this line) */
