/* Generated By:JJTree: Do not edit this line. JavaASTSynchronizedStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTSynchronizedStatement extends JavaSimpleNode {
  public JavaASTSynchronizedStatement(int id) {
    super(id);
  }

  public JavaASTSynchronizedStatement(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1620f584f5c8a95f1eec5bd1b7e405e4 (do not edit this line) */
