/* Generated By:JJTree: Do not edit this line. JavaASTEmptyStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTEmptyStatement extends JavaSimpleNode {
  public JavaASTEmptyStatement(int id) {
    super(id);
  }

  public JavaASTEmptyStatement(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a282a448887b0cc8144b5ab2daef6d4e (do not edit this line) */
