/* Generated By:JJTree: Do not edit this line. JavaASTLabeledStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTLabeledStatement extends JavaSimpleNode {
  public JavaASTLabeledStatement(int id) {
    super(id);
  }

  public JavaASTLabeledStatement(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9f67718d6e4ef26516f709fb3284b7b6 (do not edit this line) */
