/* Generated By:JJTree: Do not edit this line. JavaASTPrimitiveType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTPrimitiveType extends JavaSimpleNode {
  public JavaASTPrimitiveType(int id) {
    super(id);
  }

  public JavaASTPrimitiveType(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cbeca0686675b1ae099217719e8696f2 (do not edit this line) */
