/* Generated By:JJTree: Do not edit this line. JavaASTTypeArguments.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTTypeArguments extends JavaSimpleNode {
  public JavaASTTypeArguments(int id) {
    super(id);
  }

  public JavaASTTypeArguments(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=db32b49148889e8e522c939f8d06df9b (do not edit this line) */
