/* Generated By:JJTree: Do not edit this line. JavaASTWildcardBounds.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTWildcardBounds extends JavaSimpleNode {
  public JavaASTWildcardBounds(int id) {
    super(id);
  }

  public JavaASTWildcardBounds(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=246da1e284c0bee9bd9d168bf3422f37 (do not edit this line) */
