/* Generated By:JJTree: Do not edit this line. JavaASTTypeDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTTypeDeclaration extends JavaSimpleNode {
  public JavaASTTypeDeclaration(int id) {
    super(id);
  }

  public JavaASTTypeDeclaration(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=10b31126f7ed905d1c78808607b1fc00 (do not edit this line) */
