/* Generated By:JJTree: Do not edit this line. JavaASTMemberValuePairs.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTMemberValuePairs extends JavaSimpleNode {
  public JavaASTMemberValuePairs(int id) {
    super(id);
  }

  public JavaASTMemberValuePairs(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=03cb64c2b4824bc68c88409fb2ea7c69 (do not edit this line) */
