/* Generated By:JJTree: Do not edit this line. JavaASTPrimarySuffix.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTPrimarySuffix extends JavaSimpleNode {
  public JavaASTPrimarySuffix(int id) {
    super(id);
  }

  public JavaASTPrimarySuffix(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d99e5528659933349efc2e9830c1511b (do not edit this line) */
