/* Generated By:JJTree: Do not edit this line. JavaASTBooleanLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTBooleanLiteral extends JavaSimpleNode {
  public JavaASTBooleanLiteral(int id) {
    super(id);
  }

  public JavaASTBooleanLiteral(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=123201663d5fc18d4fcd626fa882cff2 (do not edit this line) */
