/* Generated By:JJTree: Do not edit this line. JavaASTTypeArgument.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTTypeArgument extends JavaSimpleNode {
  public JavaASTTypeArgument(int id) {
    super(id);
  }

  public JavaASTTypeArgument(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cf2da747ad20d57ef32c08ed6a0b5f49 (do not edit this line) */
