/* Generated By:JJTree: Do not edit this line. JavaASTThrowStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTThrowStatement extends JavaSimpleNode {
  public JavaASTThrowStatement(int id) {
    super(id);
  }

  public JavaASTThrowStatement(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=195dd07faabb6a0096a082ecb4fda2b3 (do not edit this line) */
