/* Generated By:JJTree: Do not edit this line. JavaASTArrayDimsAndInits.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTArrayDimsAndInits extends JavaSimpleNode {
  public JavaASTArrayDimsAndInits(int id) {
    super(id);
  }

  public JavaASTArrayDimsAndInits(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9e6a2b158025d4c600a5a6745b779779 (do not edit this line) */
