/* Generated By:JJTree: Do not edit this line. JavaASTClassOrInterfaceDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTClassOrInterfaceDeclaration extends JavaSimpleNode {
  public JavaASTClassOrInterfaceDeclaration(int id) {
    super(id);
  }

  public JavaASTClassOrInterfaceDeclaration(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=985d72ad75b55e6f9d9589c3d0ed0a55 (do not edit this line) */
