/* Generated By:JJTree: Do not edit this line. JavaASTNoParemeters.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTNoParemeters extends JavaSimpleNode {
  public JavaASTNoParemeters(int id) {
    super(id);
  }

  public JavaASTNoParemeters(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3ccd6da97b9afbbebed41aa6aed6e8d1 (do not edit this line) */
