/* Generated By:JJTree: Do not edit this line. JavaASTLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTLiteral extends JavaSimpleNode {
  public JavaASTLiteral(int id) {
    super(id);
  }

  public JavaASTLiteral(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=63e505a04bb4f5d78995a86e2754fa8e (do not edit this line) */
