/* Generated By:JJTree: Do not edit this line. JavaASTArrayInitializer.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTArrayInitializer extends JavaSimpleNode {
  public JavaASTArrayInitializer(int id) {
    super(id);
  }

  public JavaASTArrayInitializer(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ec7d55544394532dc69fe9298fcdad61 (do not edit this line) */
