/* Generated By:JJTree: Do not edit this line. JavaASTInstanceOfExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTInstanceOfExpression extends JavaSimpleNode {
  public JavaASTInstanceOfExpression(int id) {
    super(id);
  }

  public JavaASTInstanceOfExpression(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4919be6f3c9e620236082cd81aec1bd4 (do not edit this line) */
