/* Generated By:JJTree: Do not edit this line. JavaASTUnaryExpressionNotPlusMinus.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTUnaryExpressionNotPlusMinus extends JavaSimpleNode {
  public JavaASTUnaryExpressionNotPlusMinus(int id) {
    super(id);
  }

  public JavaASTUnaryExpressionNotPlusMinus(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8eef082e426d5257d222ff9a273e8b78 (do not edit this line) */
