/* Generated By:JJTree: Do not edit this line. JavaASTConditionalOrExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTConditionalOrExpression extends JavaSimpleNode {
  public JavaASTConditionalOrExpression(int id) {
    super(id);
  }

  public JavaASTConditionalOrExpression(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=45e90a4362093f17c0d478ee872eb4ef (do not edit this line) */
