/* Generated By:JJTree: Do not edit this line. JavaASTDefaultValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTDefaultValue extends JavaSimpleNode {
  public JavaASTDefaultValue(int id) {
    super(id);
  }

  public JavaASTDefaultValue(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=869686f26b561932f6eabbd7758f2a20 (do not edit this line) */
