/* Generated By:JJTree: Do not edit this line. JavaASTNormalAnnotation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTNormalAnnotation extends JavaSimpleNode {
  public JavaASTNormalAnnotation(int id) {
    super(id);
  }

  public JavaASTNormalAnnotation(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=22103041a755771a267c6ed7c76134c6 (do not edit this line) */
