/* Generated By:JJTree: Do not edit this line. JavaASTStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTStatement extends JavaSimpleNode {
  public JavaASTStatement(int id) {
    super(id);
  }

  public JavaASTStatement(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c511b9522aba659620f85e1aeaa58f11 (do not edit this line) */
