/* Generated By:JJTree: Do not edit this line. JavaASTClassOrInterfaceType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTClassOrInterfaceType extends JavaSimpleNode {
  public JavaASTClassOrInterfaceType(int id) {
    super(id);
  }

  public JavaASTClassOrInterfaceType(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0a68c69553ee4a1be67fe070202fc3eb (do not edit this line) */
