/* Generated By:JJTree: Do not edit this line. JavaASTEqualityExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTEqualityExpression extends JavaSimpleNode {
  public JavaASTEqualityExpression(int id) {
    super(id);
  }

  public JavaASTEqualityExpression(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=779d9f49a3aa39aab955c8de09b5288e (do not edit this line) */
