/* Generated By:JJTree: Do not edit this line. JavaASTMemberValuePair.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTMemberValuePair extends JavaSimpleNode {
  public JavaASTMemberValuePair(int id) {
    super(id);
  }

  public JavaASTMemberValuePair(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2b02a289f544790a3188a407f7bd0f4f (do not edit this line) */
