/* Generated By:JJTree: Do not edit this line. JavaASTFormalParameter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTFormalParameter extends JavaSimpleNode {
  public JavaASTFormalParameter(int id) {
    super(id);
  }

  public JavaASTFormalParameter(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=45d4027e2bb22a0c7142fa51f10958ae (do not edit this line) */
