/* Generated By:JJTree: Do not edit this line. JavaASTCastLookahead.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTCastLookahead extends JavaSimpleNode {
  public JavaASTCastLookahead(int id) {
    super(id);
  }

  public JavaASTCastLookahead(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9334658ab84d70a219fe9d0e951f7c62 (do not edit this line) */
