/* Generated By:JJTree: Do not edit this line. JavaASTSwitchLabel.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTSwitchLabel extends JavaSimpleNode {
  public JavaASTSwitchLabel(int id) {
    super(id);
  }

  public JavaASTSwitchLabel(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3536b92f7405f0b197f7e89564cec923 (do not edit this line) */
