/* Generated By:JJTree: Do not edit this line. JavaASTClassOrInterfaceBody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTClassOrInterfaceBody extends JavaSimpleNode {
  public JavaASTClassOrInterfaceBody(int id) {
    super(id);
  }

  public JavaASTClassOrInterfaceBody(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=44335110aee409978a8f0a522322109d (do not edit this line) */
