/* Generated By:JJTree: Do not edit this line. JavaASTDoStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTDoStatement extends JavaSimpleNode {
  public JavaASTDoStatement(int id) {
    super(id);
  }

  public JavaASTDoStatement(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c49b93cf20c02bf1ebc594cac563e9bb (do not edit this line) */
