/* Generated By:JJTree: Do not edit this line. JavaASTAndExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTAndExpression extends JavaSimpleNode {
  public JavaASTAndExpression(int id) {
    super(id);
  }

  public JavaASTAndExpression(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8777a9aada8d318d7e2795089452cc0b (do not edit this line) */
