/* Generated By:JJTree: Do not edit this line. JavaASTStatementExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTStatementExpression extends JavaSimpleNode {
  public JavaASTStatementExpression(int id) {
    super(id);
  }

  public JavaASTStatementExpression(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3fcd364a2647cf548122e0243b163645 (do not edit this line) */
