/* Generated By:JJTree: Do not edit this line. JavaASTForUpdate.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTForUpdate extends JavaSimpleNode {
  public JavaASTForUpdate(int id) {
    super(id);
  }

  public JavaASTForUpdate(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d75c222e95e6dc077001299eb18ef407 (do not edit this line) */
