/* Generated By:JJTree: Do not edit this line. JavaASTAssignmentOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTAssignmentOperator extends JavaSimpleNode {
  public JavaASTAssignmentOperator(int id) {
    super(id);
  }

  public JavaASTAssignmentOperator(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1b45a0199f77738cee8dd401e35fa52c (do not edit this line) */
