/* Generated By:JJTree: Do not edit this line. JavaASTPreIncOrDecExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTPreIncOrDecExpression extends JavaSimpleNode {
  public JavaASTPreIncOrDecExpression(int id) {
    super(id);
  }

  public JavaASTPreIncOrDecExpression(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ec4006fd27221f4234dccbb6aa03f831 (do not edit this line) */
