/* Generated By:JJTree: Do not edit this line. JavaASTAdditiveExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTAdditiveExpression extends JavaSimpleNode {
  public JavaASTAdditiveExpression(int id) {
    super(id);
  }

  public JavaASTAdditiveExpression(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2d32f2ff0b0dfa05492dc5f7d9de6ca2 (do not edit this line) */
