/* Generated By:JJTree: Do not edit this line. JavaASTReferenceType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTReferenceType extends JavaSimpleNode {
  public JavaASTReferenceType(int id) {
    super(id);
  }

  public JavaASTReferenceType(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1807646306d6a31b9e0b86221f30cea9 (do not edit this line) */
