/* Generated By:JJTree: Do not edit this line. JavaASTImplementsList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTImplementsList extends JavaSimpleNode {
  public JavaASTImplementsList(int id) {
    super(id);
  }

  public JavaASTImplementsList(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e0b2bc551647cb04d26e3482165e3b0d (do not edit this line) */
