/* Generated By:JJTree: Do not edit this line. JavaASTEnumConstant.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTEnumConstant extends JavaSimpleNode {
  public JavaASTEnumConstant(int id) {
    super(id);
  }

  public JavaASTEnumConstant(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3c6d5ae28ae79a24937383b09f045903 (do not edit this line) */
