/* Generated By:JJTree: Do not edit this line. JavaASTRoot.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTRoot extends JavaSimpleNode {
  public JavaASTRoot(int id) {
    super(id);
  }

  public JavaASTRoot(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=99cef40c631b3883296316bf004013d8 (do not edit this line) */
