/* Generated By:JJTree: Do not edit this line. JavaASTType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTType extends JavaSimpleNode {
  public JavaASTType(int id) {
    super(id);
  }

  public JavaASTType(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=32b72604bc52ad24bd299236239a5b04 (do not edit this line) */
