/* Generated By:JJTree: Do not edit this line. JavaASTNameList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTNameList extends JavaSimpleNode {
  public JavaASTNameList(int id) {
    super(id);
  }

  public JavaASTNameList(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=888b1ab6ae8f3cc95b3fa015de620feb (do not edit this line) */
