/* Generated By:JJTree: Do not edit this line. JavaASTPostfixExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTPostfixExpression extends JavaSimpleNode {
  public JavaASTPostfixExpression(int id) {
    super(id);
  }

  public JavaASTPostfixExpression(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=14ba8ba3760689ac5227da74e36be091 (do not edit this line) */
