/* Generated By:JJTree: Do not edit this line. JavaASTVariableDeclaratorId.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=JavaAST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.bupt.cmp.ast.java;

public
class JavaASTVariableDeclaratorId extends JavaSimpleNode {
  public JavaASTVariableDeclaratorId(int id) {
    super(id);
  }

  public JavaASTVariableDeclaratorId(JavaTreeParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1f2a53644f080dc7905390ea096458b6 (do not edit this line) */
