/* Generated By:JavaCC: Do not edit this line. CPPParserTokenManager.java */
package com.bupt.cmp.parser.cpp;

/** Token Manager. */
public class CPPParserTokenManager implements CPPParserConstants
{
   static int beginLine;
   static int beginCol;
   static boolean lineDirective = false;

   static void resetBeginLineCol()
   {
   }

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private int jjMoveStringLiteralDfa0_1()
{
   return jjMoveNfa_1(0, 0);
}
private int jjMoveNfa_1(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 1;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  kind = 9;
                  jjstateSet[jjnewStateCnt++] = 0;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 1 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1, long active2)
{
   switch (pos)
   {
      case 0:
         if ((active1 & 0x80000000001c0000L) != 0L || (active2 & 0x100000L) != 0L)
         {
            jjmatchedKind = 149;
            return 6;
         }
         if ((active1 & 0x4075000040000000L) != 0L || (active2 & 0x1L) != 0L)
         {
            jjmatchedKind = 149;
            return 2;
         }
         if ((active1 & 0x3f8affffbfe3fff0L) != 0L || (active2 & 0xc0000L) != 0L)
         {
            jjmatchedKind = 149;
            return 41;
         }
         if ((active0 & 0x40000000L) != 0L || (active1 & 0x5L) != 0L)
            return 9;
         if ((active0 & 0x100L) != 0L)
            return 98;
         return -1;
      case 1:
         if ((active1 & 0x8000000000000000L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 149;
               jjmatchedPos = 1;
            }
            return 5;
         }
         if ((active1 & 0x406000L) != 0L)
            return 41;
         if ((active1 & 0x4020000000000000L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 149;
               jjmatchedPos = 1;
            }
            return 1;
         }
         if ((active1 & 0x3fdfffffffbf9ff0L) != 0L || (active2 & 0x1c0001L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 149;
               jjmatchedPos = 1;
            }
            return 41;
         }
         return -1;
      case 2:
         if ((active1 & 0x3fdffff5ffb7dff0L) != 0L || (active2 & 0x1c0001L) != 0L)
         {
            jjmatchedKind = 149;
            jjmatchedPos = 2;
            return 41;
         }
         if ((active1 & 0x8000000000000000L) != 0L)
         {
            jjmatchedKind = 149;
            jjmatchedPos = 2;
            return 4;
         }
         if ((active1 & 0x20000a00080000L) != 0L)
            return 41;
         if ((active1 & 0x4000000000000000L) != 0L)
         {
            jjmatchedKind = 149;
            jjmatchedPos = 2;
            return 99;
         }
         return -1;
      case 3:
         if ((active1 & 0x8000000000000000L) != 0L)
         {
            jjmatchedKind = 149;
            jjmatchedPos = 3;
            return 99;
         }
         if ((active1 & 0x3bcffff0ff965ea0L) != 0L || (active2 & 0x1c0001L) != 0L)
         {
            jjmatchedKind = 149;
            jjmatchedPos = 3;
            return 41;
         }
         if ((active1 & 0x4410000500218150L) != 0L)
            return 41;
         return -1;
      case 4:
         if ((active1 & 0x90808400200402a0L) != 0L || (active2 & 0x80001L) != 0L)
            return 41;
         if ((active1 & 0x2b4f7bf0df925c00L) != 0L || (active2 & 0x140000L) != 0L)
         {
            if (jjmatchedPos != 4)
            {
               jjmatchedKind = 149;
               jjmatchedPos = 4;
            }
            return 41;
         }
         return -1;
      case 5:
         if ((active1 & 0xa7a4048925000L) != 0L)
            return 41;
         if ((active1 & 0x2b4501b0b7000c00L) != 0L || (active2 & 0x140000L) != 0L)
         {
            if (jjmatchedPos != 5)
            {
               jjmatchedKind = 149;
               jjmatchedPos = 5;
            }
            return 41;
         }
         return -1;
      case 6:
         if ((active1 & 0x290501a03e000400L) != 0L || (active2 & 0x40000L) != 0L)
         {
            jjmatchedKind = 149;
            jjmatchedPos = 6;
            return 41;
         }
         if ((active1 & 0x240001081000800L) != 0L || (active2 & 0x100000L) != 0L)
            return 41;
         return -1;
      case 7:
         if ((active1 & 0x2905010002000400L) != 0L)
            return 41;
         if ((active1 & 0xa03c000000L) != 0L || (active2 & 0x40000L) != 0L)
         {
            jjmatchedKind = 149;
            jjmatchedPos = 7;
            return 41;
         }
         return -1;
      case 8:
         if ((active1 & 0x2000000000L) != 0L || (active2 & 0x40000L) != 0L)
            return 41;
         if ((active1 & 0x803c000000L) != 0L)
         {
            jjmatchedKind = 149;
            jjmatchedPos = 8;
            return 41;
         }
         return -1;
      case 9:
         if ((active1 & 0x1c000000L) != 0L)
         {
            jjmatchedKind = 149;
            jjmatchedPos = 9;
            return 41;
         }
         if ((active1 & 0x8020000000L) != 0L)
            return 41;
         return -1;
      case 10:
         if ((active1 & 0x14000000L) != 0L)
         {
            jjmatchedKind = 149;
            jjmatchedPos = 10;
            return 41;
         }
         if ((active1 & 0x8000000L) != 0L)
            return 41;
         return -1;
      case 11:
         if ((active1 & 0x4000000L) != 0L)
            return 41;
         if ((active1 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 149;
            jjmatchedPos = 11;
            return 41;
         }
         return -1;
      case 12:
         if ((active1 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 149;
            jjmatchedPos = 12;
            return 41;
         }
         return -1;
      case 13:
         if ((active1 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 149;
            jjmatchedPos = 13;
            return 41;
         }
         return -1;
      case 14:
         if ((active1 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 149;
            jjmatchedPos = 14;
            return 41;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1, long active2)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1, active2), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 33:
         jjmatchedKind = 63;
         return jjMoveStringLiteralDfa1_0(0x1000000000000L, 0x0L, 0x0L);
      case 35:
         return jjStartNfaWithStates_0(0, 8, 98);
      case 37:
         jjmatchedKind = 59;
         return jjMoveStringLiteralDfa1_0(0x400000000L, 0x0L, 0x0L);
      case 38:
         jjmatchedKind = 46;
         return jjMoveStringLiteralDfa1_0(0x88000000000L, 0x0L, 0x0L);
      case 40:
         return jjStopAtPos(0, 23);
      case 41:
         return jjStopAtPos(0, 24);
      case 42:
         jjmatchedKind = 57;
         return jjMoveStringLiteralDfa1_0(0x100000000L, 0x0L, 0x0L);
      case 43:
         jjmatchedKind = 55;
         return jjMoveStringLiteralDfa1_0(0x1000000800000000L, 0x0L, 0x0L);
      case 44:
         return jjStopAtPos(0, 28);
      case 45:
         jjmatchedKind = 56;
         return jjMoveStringLiteralDfa1_0(0x2000001000000000L, 0xaL, 0x0L);
      case 46:
         jjmatchedKind = 64;
         return jjMoveStringLiteralDfa1_0(0x40000000L, 0x4L, 0x0L);
      case 47:
         jjmatchedKind = 58;
         return jjMoveStringLiteralDfa1_0(0x200000030L, 0x0L, 0x0L);
      case 58:
         jjmatchedKind = 26;
         return jjMoveStringLiteralDfa1_0(0x2000000L, 0x0L, 0x0L);
      case 59:
         return jjStopAtPos(0, 27);
      case 60:
         jjmatchedKind = 49;
         return jjMoveStringLiteralDfa1_0(0x28002000000000L, 0x0L, 0x0L);
      case 61:
         jjmatchedKind = 31;
         return jjMoveStringLiteralDfa1_0(0x800000000000L, 0x0L, 0x0L);
      case 62:
         jjmatchedKind = 50;
         return jjMoveStringLiteralDfa1_0(0x50004000000000L, 0x0L, 0x0L);
      case 63:
         return jjStopAtPos(0, 29);
      case 91:
         return jjStopAtPos(0, 21);
      case 93:
         return jjStopAtPos(0, 22);
      case 94:
         jjmatchedKind = 45;
         return jjMoveStringLiteralDfa1_0(0x10000000000L, 0x0L, 0x0L);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x10L, 0x0L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x100000020L, 0x0L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x8000200007c0L, 0x0L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x4007800L, 0x0L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x8000002038000L, 0x0L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x80000000001c0000L, 0x100000L);
      case 103:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x200000L, 0x0L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x200c00000L, 0x0L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x400000000L, 0x0L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x1000000L, 0x0L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x800000000L, 0x40000L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x2000000000000000L, 0x0L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x7000000000L, 0x0L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x38010000000L, 0x0L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x27c0008000000L, 0x0L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x4075000040000000L, 0x1L);
      case 117:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x180000000000000L, 0x80000L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x0L, 0xe00000000000000L, 0x0L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x1000000080000000L, 0x0L);
      case 123:
         return jjStopAtPos(0, 19);
      case 124:
         jjmatchedKind = 44;
         return jjMoveStringLiteralDfa1_0(0x60000000000L, 0x0L, 0x0L);
      case 125:
         return jjStopAtPos(0, 20);
      case 126:
         return jjStopAtPos(0, 62);
      default :
         return jjMoveNfa_0(3, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0, long active1, long active2)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1, active2);
      return 1;
   }
   switch(curChar)
   {
      case 38:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStopAtPos(1, 43);
         break;
      case 42:
         if ((active0 & 0x20L) != 0L)
            return jjStopAtPos(1, 5);
         else if ((active1 & 0x4L) != 0L)
            return jjStopAtPos(1, 66);
         break;
      case 43:
         if ((active0 & 0x1000000000000000L) != 0L)
            return jjStopAtPos(1, 60);
         break;
      case 45:
         if ((active0 & 0x2000000000000000L) != 0L)
            return jjStopAtPos(1, 61);
         break;
      case 46:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000L, active1, 0L, active2, 0L);
      case 47:
         if ((active0 & 0x10L) != 0L)
            return jjStopAtPos(1, 4);
         break;
      case 58:
         if ((active0 & 0x2000000L) != 0L)
            return jjStopAtPos(1, 25);
         break;
      case 60:
         if ((active0 & 0x20000000000000L) != 0L)
         {
            jjmatchedKind = 53;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000000L, active1, 0L, active2, 0L);
      case 61:
         if ((active0 & 0x100000000L) != 0L)
            return jjStopAtPos(1, 32);
         else if ((active0 & 0x200000000L) != 0L)
            return jjStopAtPos(1, 33);
         else if ((active0 & 0x400000000L) != 0L)
            return jjStopAtPos(1, 34);
         else if ((active0 & 0x800000000L) != 0L)
            return jjStopAtPos(1, 35);
         else if ((active0 & 0x1000000000L) != 0L)
            return jjStopAtPos(1, 36);
         else if ((active0 & 0x8000000000L) != 0L)
            return jjStopAtPos(1, 39);
         else if ((active0 & 0x10000000000L) != 0L)
            return jjStopAtPos(1, 40);
         else if ((active0 & 0x20000000000L) != 0L)
            return jjStopAtPos(1, 41);
         else if ((active0 & 0x800000000000L) != 0L)
            return jjStopAtPos(1, 47);
         else if ((active0 & 0x1000000000000L) != 0L)
            return jjStopAtPos(1, 48);
         else if ((active0 & 0x8000000000000L) != 0L)
            return jjStopAtPos(1, 51);
         else if ((active0 & 0x10000000000000L) != 0L)
            return jjStopAtPos(1, 52);
         break;
      case 62:
         if ((active0 & 0x40000000000000L) != 0L)
         {
            jjmatchedKind = 54;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x2L) != 0L)
         {
            jjmatchedKind = 65;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000000L, active1, 0x8L, active2, 0L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x80000000000000c0L, active2, 0x40000L);
      case 99:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x80000000L, active2, 0L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x4038810001800L, active2, 0L);
      case 102:
         if ((active1 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(1, 86, 41);
         break;
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x1010040000000100L, active2, 0x1L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x200180000000000L, active2, 0x100000L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x800000048000L, active2, 0L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x180000200810000L, active2, 0L);
      case 111:
         if ((active1 & 0x2000L) != 0L)
         {
            jjmatchedKind = 77;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0xc00000520284600L, active2, 0L);
      case 112:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x2000000000000000L, active2, 0L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x4020003000100020L, active2, 0L);
      case 115:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0L, active2, 0x80000L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x600008000000L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x4001000010L, active2, 0L);
      case 119:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x2000000000000L, active2, 0L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x8000002020000L, active2, 0L);
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x41000044000000L, active2, 0L);
      case 124:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStopAtPos(1, 42);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1, active2);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(0, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1, active2);
      return 2;
   }
   switch(curChar)
   {
      case 42:
         if ((active1 & 0x8L) != 0L)
            return jjStopAtPos(2, 67);
         break;
      case 46:
         if ((active0 & 0x40000000L) != 0L)
            return jjStopAtPos(2, 30);
         break;
      case 61:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStopAtPos(2, 37);
         else if ((active0 & 0x4000000000L) != 0L)
            return jjStopAtPos(2, 38);
         break;
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0xa00008000100L, active2, 0L);
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x4000000000L, active2, 0L);
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x8000000000L, active2, 0L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x2000000000000020L, active2, 0L);
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x800L, active2, 0L);
      case 103:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x90000000000L, active2, 0L);
      case 104:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x80000000L, active2, 0L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x1492001010100000L, active2, 0x80000L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x8800000000801000L, active2, 0L);
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x4000000000000L, active2, 0x40000L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x424000600L, active2, 0x100000L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x42100040000L, active2, 0L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x49000042000000L, active2, 0L);
      case 114:
         if ((active1 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(2, 83, 41);
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x200400000000000L, active2, 0x1L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x100000000008040L, active2, 0L);
      case 116:
         if ((active1 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(2, 97, 41);
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x20001220090L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x4000000000014000L, active2, 0L);
      case 119:
         if ((active1 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(2, 99, 41);
         break;
      case 121:
         if ((active1 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 117, 41);
         break;
      case 122:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x100000000000L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1, active2);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1, long old2, long active2)
{
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(1, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, 0L, active1, active2);
      return 3;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa4_0(active1, 0x800000085040820L, active2, 0x100000L);
      case 98:
         return jjMoveStringLiteralDfa4_0(active1, 0x4000L, active2, 0L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active1, 0x80L, active2, 0L);
      case 100:
         if ((active1 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 122, 41);
         break;
      case 101:
         if ((active1 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(3, 70, 41);
         else if ((active1 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(3, 79, 41);
         else if ((active1 & 0x4000000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 126, 41);
         return jjMoveStringLiteralDfa4_0(active1, 0x41108040121000L, active2, 0x40000L);
      case 103:
         if ((active1 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(3, 98, 41);
         break;
      case 105:
         return jjMoveStringLiteralDfa4_0(active1, 0x100010000800000L, active2, 0L);
      case 108:
         if ((active1 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(3, 96, 41);
         return jjMoveStringLiteralDfa4_0(active1, 0x1000004002000000L, active2, 0L);
      case 109:
         if ((active1 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(3, 80, 41);
         break;
      case 110:
         return jjMoveStringLiteralDfa4_0(active1, 0x80010000000L, active2, 0x80000L);
      case 111:
         if ((active1 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(3, 68, 41);
         else if ((active1 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(3, 85, 41);
         return jjMoveStringLiteralDfa4_0(active1, 0x88000000000000L, active2, 0x1L);
      case 112:
         return jjMoveStringLiteralDfa4_0(active1, 0x4000000000000L, active2, 0L);
      case 114:
         if ((active1 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(3, 72, 41);
         return jjMoveStringLiteralDfa4_0(active1, 0x2000040000000000L, active2, 0L);
      case 115:
         if ((active1 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 116, 41);
         return jjMoveStringLiteralDfa4_0(active1, 0x8000800020000200L, active2, 0L);
      case 116:
         return jjMoveStringLiteralDfa4_0(active1, 0x202202008000400L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active1, 0x420000000000L, active2, 0L);
      case 118:
         return jjMoveStringLiteralDfa4_0(active1, 0x1000000000L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(2, 0L, active1, active2);
}
private int jjMoveStringLiteralDfa4_0(long old1, long active1, long old2, long active2)
{
   if (((active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(2, 0L, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, 0L, active1, active2);
      return 4;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa5_0(active1, 0x2000001000000000L, active2, 0L);
      case 98:
         return jjMoveStringLiteralDfa5_0(active1, 0x1000000L, active2, 0L);
      case 99:
         return jjMoveStringLiteralDfa5_0(active1, 0x2408000000000L, active2, 0L);
      case 100:
         return jjMoveStringLiteralDfa5_0(active1, 0x40000000000000L, active2, 0L);
      case 101:
         if ((active1 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 124, 41);
         else if ((active1 & 0x8000000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 127, 41);
         return jjMoveStringLiteralDfa5_0(active1, 0x82000000000L, active2, 0L);
      case 103:
         if ((active2 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(4, 147, 41);
         return jjMoveStringLiteralDfa5_0(active1, 0x100000000000000L, active2, 0L);
      case 104:
         if ((active1 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(4, 71, 41);
         break;
      case 105:
         return jjMoveStringLiteralDfa5_0(active1, 0x20404a000400L, active2, 0L);
      case 107:
         if ((active1 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(4, 69, 41);
         break;
      case 108:
         return jjMoveStringLiteralDfa5_0(active1, 0x4000000004000L, active2, 0x100000L);
      case 109:
         return jjMoveStringLiteralDfa5_0(active1, 0x4000000L, active2, 0L);
      case 110:
         if ((active1 & 0x80000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 119, 41);
         return jjMoveStringLiteralDfa5_0(active1, 0x1000000900000L, active2, 0L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active1, 0x100000000000L, active2, 0L);
      case 114:
         return jjMoveStringLiteralDfa5_0(active1, 0x8020080020000L, active2, 0L);
      case 115:
         if ((active1 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 111, 41);
         return jjMoveStringLiteralDfa5_0(active1, 0x10000000000L, active2, 0x40000L);
      case 116:
         if ((active1 & 0x200L) != 0L)
         {
            jjmatchedKind = 73;
            jjmatchedPos = 4;
         }
         else if ((active1 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(4, 82, 41);
         else if ((active1 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 106, 41);
         return jjMoveStringLiteralDfa5_0(active1, 0x800000030001000L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active1, 0x200000000000800L, active2, 0L);
      case 119:
         if ((active2 & 0x1L) != 0L)
            return jjStartNfaWithStates_0(4, 128, 41);
         break;
      default :
         break;
   }
   return jjStartNfa_0(3, 0L, active1, active2);
}
private int jjMoveStringLiteralDfa5_0(long old1, long active1, long old2, long active2)
{
   if (((active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(3, 0L, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, 0L, active1, active2);
      return 5;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa6_0(active1, 0xa0000000L, active2, 0L);
      case 97:
         return jjMoveStringLiteralDfa6_0(active1, 0x205000000000000L, active2, 0L);
      case 99:
         if ((active1 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 102, 41);
         else if ((active1 & 0x200000000000L) != 0L)
         {
            jjmatchedKind = 109;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active1, 0x200a000000L, active2, 0L);
      case 100:
         if ((active1 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(5, 84, 41);
         else if ((active1 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(5, 94, 41);
         else if ((active1 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 107, 41);
         break;
      case 101:
         if ((active1 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(5, 76, 41);
         else if ((active1 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(5, 78, 41);
         else if ((active1 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(5, 87, 41);
         return jjMoveStringLiteralDfa6_0(active1, 0x40000010000000L, active2, 0L);
      case 102:
         if ((active1 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 108, 41);
         break;
      case 104:
         if ((active1 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 113, 41);
         break;
      case 105:
         return jjMoveStringLiteralDfa6_0(active1, 0x800000004000000L, active2, 0L);
      case 108:
         return jjMoveStringLiteralDfa6_0(active1, 0x8001000800L, active2, 0x100000L);
      case 110:
         if ((active1 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(5, 81, 41);
         else if ((active1 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 105, 41);
         return jjMoveStringLiteralDfa6_0(active1, 0x100000000000400L, active2, 0L);
      case 112:
         return jjMoveStringLiteralDfa6_0(active1, 0L, active2, 0x40000L);
      case 116:
         if ((active1 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 110, 41);
         else if ((active1 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 115, 41);
         return jjMoveStringLiteralDfa6_0(active1, 0x2000011000000000L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(4, 0L, active1, active2);
}
private int jjMoveStringLiteralDfa6_0(long old1, long active1, long old2, long active2)
{
   if (((active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(4, 0L, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, 0L, active1, active2);
      return 6;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa7_0(active1, 0x8000000L, active2, 0L);
      case 97:
         return jjMoveStringLiteralDfa7_0(active1, 0x8000000000L, active2, 0x40000L);
      case 99:
         return jjMoveStringLiteralDfa7_0(active1, 0x24000000L, active2, 0L);
      case 101:
         if ((active1 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(6, 88, 41);
         else if ((active1 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 100, 41);
         return jjMoveStringLiteralDfa7_0(active1, 0x100010000000000L, active2, 0L);
      case 102:
         if ((active1 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 118, 41);
         break;
      case 105:
         return jjMoveStringLiteralDfa7_0(active1, 0x2000000L, active2, 0L);
      case 108:
         if ((active1 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 121, 41);
         return jjMoveStringLiteralDfa7_0(active1, 0x800000000000000L, active2, 0L);
      case 109:
         return jjMoveStringLiteralDfa7_0(active1, 0x1000000000000L, active2, 0L);
      case 111:
         return jjMoveStringLiteralDfa7_0(active1, 0x2000000000000000L, active2, 0L);
      case 114:
         return jjMoveStringLiteralDfa7_0(active1, 0x10000000L, active2, 0L);
      case 116:
         if ((active1 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(6, 75, 41);
         else if ((active1 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(6, 95, 41);
         return jjMoveStringLiteralDfa7_0(active1, 0x4002000000000L, active2, 0L);
      case 117:
         return jjMoveStringLiteralDfa7_0(active1, 0x400L, active2, 0L);
      case 121:
         if ((active2 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(6, 148, 41);
         break;
      default :
         break;
   }
   return jjStartNfa_0(5, 0L, active1, active2);
}
private int jjMoveStringLiteralDfa7_0(long old1, long active1, long old2, long active2)
{
   if (((active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(5, 0L, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, 0L, active1, active2);
      return 7;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa8_0(active1, 0x4000000L, active2, 0L);
      case 97:
         return jjMoveStringLiteralDfa8_0(active1, 0x20000000L, active2, 0L);
      case 99:
         return jjMoveStringLiteralDfa8_0(active1, 0x8000000L, active2, 0x40000L);
      case 100:
         if ((active1 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 120, 41);
         break;
      case 101:
         if ((active1 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(7, 74, 41);
         else if ((active1 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 112, 41);
         else if ((active1 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 114, 41);
         else if ((active1 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 123, 41);
         return jjMoveStringLiteralDfa8_0(active1, 0x2000000000L, active2, 0L);
      case 112:
         return jjMoveStringLiteralDfa8_0(active1, 0x10000000L, active2, 0L);
      case 114:
         if ((active1 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 104, 41);
         else if ((active1 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 125, 41);
         return jjMoveStringLiteralDfa8_0(active1, 0x8000000000L, active2, 0L);
      case 116:
         if ((active1 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(7, 89, 41);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, 0L, active1, active2);
}
private int jjMoveStringLiteralDfa8_0(long old1, long active1, long old2, long active2)
{
   if (((active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(6, 0L, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, 0L, active1, active2);
      return 8;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa9_0(active1, 0x8000000L, active2, 0L);
      case 99:
         return jjMoveStringLiteralDfa9_0(active1, 0x4000000L, active2, 0L);
      case 100:
         if ((active1 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 101, 41);
         break;
      case 101:
         if ((active2 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(8, 146, 41);
         return jjMoveStringLiteralDfa9_0(active1, 0x8000000000L, active2, 0L);
      case 114:
         return jjMoveStringLiteralDfa9_0(active1, 0x10000000L, active2, 0L);
      case 115:
         return jjMoveStringLiteralDfa9_0(active1, 0x20000000L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(7, 0L, active1, active2);
}
private int jjMoveStringLiteralDfa9_0(long old1, long active1, long old2, long active2)
{
   if (((active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(7, 0L, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, 0L, active1, 0L);
      return 9;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa10_0(active1, 0x4000000L);
      case 100:
         if ((active1 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 103, 41);
         break;
      case 101:
         return jjMoveStringLiteralDfa10_0(active1, 0x10000000L);
      case 115:
         return jjMoveStringLiteralDfa10_0(active1, 0x8000000L);
      case 116:
         if ((active1 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(9, 93, 41);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, 0L, active1, 0L);
}
private int jjMoveStringLiteralDfa10_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(8, 0L, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, 0L, active1, 0L);
      return 10;
   }
   switch(curChar)
   {
      case 115:
         return jjMoveStringLiteralDfa11_0(active1, 0x4000000L);
      case 116:
         if ((active1 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(10, 91, 41);
         return jjMoveStringLiteralDfa11_0(active1, 0x10000000L);
      default :
         break;
   }
   return jjStartNfa_0(9, 0L, active1, 0L);
}
private int jjMoveStringLiteralDfa11_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(9, 0L, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, 0L, active1, 0L);
      return 11;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa12_0(active1, 0x10000000L);
      case 116:
         if ((active1 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(11, 90, 41);
         break;
      default :
         break;
   }
   return jjStartNfa_0(10, 0L, active1, 0L);
}
private int jjMoveStringLiteralDfa12_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(10, 0L, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, 0L, active1, 0L);
      return 12;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa13_0(active1, 0x10000000L);
      default :
         break;
   }
   return jjStartNfa_0(11, 0L, active1, 0L);
}
private int jjMoveStringLiteralDfa13_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(11, 0L, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, 0L, active1, 0L);
      return 13;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa14_0(active1, 0x10000000L);
      default :
         break;
   }
   return jjStartNfa_0(12, 0L, active1, 0L);
}
private int jjMoveStringLiteralDfa14_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(12, 0L, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(13, 0L, active1, 0L);
      return 14;
   }
   switch(curChar)
   {
      case 115:
         return jjMoveStringLiteralDfa15_0(active1, 0x10000000L);
      default :
         break;
   }
   return jjStartNfa_0(13, 0L, active1, 0L);
}
private int jjMoveStringLiteralDfa15_0(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return jjStartNfa_0(13, 0L, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(14, 0L, active1, 0L);
      return 15;
   }
   switch(curChar)
   {
      case 116:
         if ((active1 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(15, 92, 41);
         break;
      default :
         break;
   }
   return jjStartNfa_0(14, 0L, active1, 0L);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 98;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 99:
               case 41:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 149)
                     kind = 149;
                  jjCheckNAdd(41);
                  break;
               case 3:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 5);
                  else if (curChar == 35)
                     jjCheckNAddStates(6, 9);
                  else if (curChar == 34)
                     jjCheckNAddStates(10, 12);
                  else if (curChar == 39)
                     jjCheckNAddStates(13, 15);
                  else if (curChar == 46)
                     jjCheckNAdd(9);
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 134)
                        kind = 134;
                     jjCheckNAddStates(16, 23);
                  }
                  else if (curChar == 48)
                     jjAddStates(24, 27);
                  if (curChar == 48)
                  {
                     if (kind > 130)
                        kind = 130;
                     jjCheckNAddStates(28, 35);
                  }
                  break;
               case 6:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 149)
                     kind = 149;
                  jjCheckNAdd(41);
                  break;
               case 5:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 149)
                     kind = 149;
                  jjCheckNAdd(41);
                  break;
               case 4:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 149)
                     kind = 149;
                  jjCheckNAdd(41);
                  break;
               case 2:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 149)
                     kind = 149;
                  jjCheckNAdd(41);
                  break;
               case 1:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 149)
                     kind = 149;
                  jjCheckNAdd(41);
                  break;
               case 98:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 7)
                        kind = 7;
                  }
                  else if ((0x100000200L & l) != 0L)
                     jjCheckNAddTwoStates(48, 49);
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddTwoStates(43, 47);
                  break;
               case 8:
                  if (curChar == 46)
                     jjCheckNAdd(9);
                  break;
               case 9:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 142)
                     kind = 142;
                  jjCheckNAddStates(36, 38);
                  break;
               case 11:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(12);
                  break;
               case 12:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 142)
                     kind = 142;
                  jjCheckNAddTwoStates(12, 13);
                  break;
               case 14:
                  if (curChar == 39)
                     jjCheckNAddStates(13, 15);
                  break;
               case 15:
                  if ((0xffffff7fffffdbffL & l) != 0L)
                     jjCheckNAddStates(13, 15);
                  break;
               case 17:
                  if ((0x8000008400000000L & l) != 0L)
                     jjCheckNAddStates(13, 15);
                  break;
               case 18:
                  if (curChar == 39 && kind > 144)
                     kind = 144;
                  break;
               case 19:
                  if (curChar == 48)
                     jjCheckNAddStates(39, 42);
                  break;
               case 20:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(39, 42);
                  break;
               case 21:
                  if ((0x3fe000000000000L & l) != 0L)
                     jjCheckNAddStates(43, 46);
                  break;
               case 22:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(43, 46);
                  break;
               case 23:
                  if (curChar == 48)
                     jjAddStates(47, 48);
                  break;
               case 25:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(49, 52);
                  break;
               case 27:
                  if (curChar == 34)
                     jjCheckNAddStates(10, 12);
                  break;
               case 28:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     jjCheckNAddStates(10, 12);
                  break;
               case 30:
                  if ((0x8000008400000000L & l) != 0L)
                     jjCheckNAddStates(10, 12);
                  break;
               case 31:
                  if (curChar == 34 && kind > 145)
                     kind = 145;
                  break;
               case 32:
                  if (curChar == 48)
                     jjCheckNAddStates(53, 56);
                  break;
               case 33:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(53, 56);
                  break;
               case 34:
                  if ((0x3fe000000000000L & l) != 0L)
                     jjCheckNAddStates(57, 60);
                  break;
               case 35:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(57, 60);
                  break;
               case 36:
                  if (curChar == 48)
                     jjAddStates(61, 62);
                  break;
               case 38:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(63, 66);
                  break;
               case 42:
                  if (curChar == 35)
                     jjCheckNAddStates(6, 9);
                  break;
               case 43:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddTwoStates(43, 47);
                  break;
               case 48:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddTwoStates(48, 49);
                  break;
               case 49:
                  if ((0x3ff000000000000L & l) != 0L && kind > 7)
                     kind = 7;
                  break;
               case 50:
                  if (curChar != 48)
                     break;
                  if (kind > 130)
                     kind = 130;
                  jjCheckNAddStates(28, 35);
                  break;
               case 51:
                  if ((0xff000000000000L & l) == 0L)
                     break;
                  if (kind > 130)
                     kind = 130;
                  jjCheckNAdd(51);
                  break;
               case 52:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(52, 53);
                  break;
               case 54:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(54, 55);
                  break;
               case 56:
                  if ((0xff000000000000L & l) != 0L)
                     jjCheckNAddStates(67, 69);
                  break;
               case 61:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 134)
                     kind = 134;
                  jjCheckNAddStates(16, 23);
                  break;
               case 62:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 134)
                     kind = 134;
                  jjCheckNAdd(62);
                  break;
               case 63:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(63, 64);
                  break;
               case 65:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(65, 66);
                  break;
               case 67:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(70, 72);
                  break;
               case 72:
                  if (curChar == 48)
                     jjAddStates(24, 27);
                  break;
               case 74:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 138)
                     kind = 138;
                  jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 76:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 139)
                     kind = 139;
                  jjAddStates(73, 74);
                  break;
               case 79:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjAddStates(75, 76);
                  break;
               case 82:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjAddStates(77, 79);
                  break;
               case 87:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(0, 5);
                  break;
               case 88:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(88, 89);
                  break;
               case 89:
                  if (curChar != 46)
                     break;
                  if (kind > 142)
                     kind = 142;
                  jjCheckNAddStates(80, 82);
                  break;
               case 90:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 142)
                     kind = 142;
                  jjCheckNAddStates(80, 82);
                  break;
               case 91:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(91, 8);
                  break;
               case 92:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(92, 93);
                  break;
               case 94:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(95);
                  break;
               case 95:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 143)
                     kind = 143;
                  jjCheckNAddTwoStates(95, 96);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 99:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 149)
                        kind = 149;
                     jjCheckNAdd(41);
                  }
                  if (curChar == 101)
                  {
                     if (kind > 129)
                        kind = 129;
                  }
                  break;
               case 3:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 149)
                        kind = 149;
                     jjCheckNAdd(41);
                  }
                  if (curChar == 76)
                     jjAddStates(83, 84);
                  else if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 6;
                  else if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 6:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 149)
                        kind = 149;
                     jjCheckNAdd(41);
                  }
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 5:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 149)
                        kind = 149;
                     jjCheckNAdd(41);
                  }
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 4:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 149)
                        kind = 149;
                     jjCheckNAdd(41);
                  }
                  if (curChar == 115)
                     jjCheckNAdd(0);
                  break;
               case 2:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 149)
                        kind = 149;
                     jjCheckNAdd(41);
                  }
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 1:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 149)
                        kind = 149;
                     jjCheckNAdd(41);
                  }
                  if (curChar == 117)
                     jjCheckNAdd(0);
                  break;
               case 98:
               case 47:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 0:
                  if (curChar == 101 && kind > 129)
                     kind = 129;
                  break;
               case 7:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 10:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(85, 86);
                  break;
               case 13:
                  if ((0x104000001040L & l) != 0L && kind > 142)
                     kind = 142;
                  break;
               case 15:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(13, 15);
                  break;
               case 16:
                  if (curChar == 92)
                     jjAddStates(87, 90);
                  break;
               case 17:
                  if ((0x54404610000000L & l) != 0L)
                     jjCheckNAddStates(13, 15);
                  break;
               case 24:
                  if (curChar == 120)
                     jjCheckNAdd(25);
                  break;
               case 25:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(49, 52);
                  break;
               case 26:
                  if (curChar == 88)
                     jjCheckNAdd(25);
                  break;
               case 28:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(10, 12);
                  break;
               case 29:
                  if (curChar == 92)
                     jjAddStates(91, 94);
                  break;
               case 30:
                  if ((0x54404610000000L & l) != 0L)
                     jjCheckNAddStates(10, 12);
                  break;
               case 37:
                  if (curChar == 120)
                     jjCheckNAdd(38);
                  break;
               case 38:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(63, 66);
                  break;
               case 39:
                  if (curChar == 88)
                     jjCheckNAdd(38);
                  break;
               case 40:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 149)
                     kind = 149;
                  jjCheckNAdd(41);
                  break;
               case 41:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 149)
                     kind = 149;
                  jjCheckNAdd(41);
                  break;
               case 44:
                  if (curChar == 101 && kind > 6)
                     kind = 6;
                  break;
               case 45:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 46:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 53:
                  if ((0x100000001000L & l) != 0L && kind > 131)
                     kind = 131;
                  break;
               case 55:
                  if ((0x20000000200000L & l) != 0L && kind > 132)
                     kind = 132;
                  break;
               case 57:
                  if ((0x100000001000L & l) != 0L && kind > 133)
                     kind = 133;
                  break;
               case 58:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 59:
                  if ((0x20000000200000L & l) != 0L && kind > 133)
                     kind = 133;
                  break;
               case 60:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 59;
                  break;
               case 64:
                  if ((0x20100000201000L & l) != 0L && kind > 135)
                     kind = 135;
                  break;
               case 66:
                  if ((0x20000000200000L & l) != 0L && kind > 136)
                     kind = 136;
                  break;
               case 68:
                  if ((0x100000001000L & l) != 0L && kind > 137)
                     kind = 137;
                  break;
               case 69:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 70:
                  if ((0x20000000200000L & l) != 0L && kind > 137)
                     kind = 137;
                  break;
               case 71:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 73:
                  if ((0x100000001000000L & l) != 0L)
                     jjCheckNAdd(74);
                  break;
               case 74:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 138)
                     kind = 138;
                  jjCheckNAdd(74);
                  break;
               case 75:
                  if ((0x100000001000000L & l) != 0L)
                     jjCheckNAdd(76);
                  break;
               case 76:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 139)
                     kind = 139;
                  jjCheckNAddTwoStates(76, 77);
                  break;
               case 77:
                  if ((0x20100000201000L & l) != 0L && kind > 139)
                     kind = 139;
                  break;
               case 78:
                  if ((0x100000001000000L & l) != 0L)
                     jjCheckNAdd(79);
                  break;
               case 79:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(79, 80);
                  break;
               case 80:
                  if ((0x20000000200000L & l) != 0L && kind > 140)
                     kind = 140;
                  break;
               case 81:
                  if ((0x100000001000000L & l) != 0L)
                     jjCheckNAdd(82);
                  break;
               case 82:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(77, 79);
                  break;
               case 83:
                  if ((0x100000001000L & l) != 0L && kind > 141)
                     kind = 141;
                  break;
               case 84:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 83;
                  break;
               case 85:
                  if ((0x20000000200000L & l) != 0L && kind > 141)
                     kind = 141;
                  break;
               case 86:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 93:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(95, 96);
                  break;
               case 96:
                  if ((0x104000001040L & l) != 0L && kind > 143)
                     kind = 143;
                  break;
               case 97:
                  if (curChar == 76)
                     jjAddStates(83, 84);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 15:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(13, 15);
                  break;
               case 28:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(10, 12);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 98 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
private int jjMoveStringLiteralDfa0_2()
{
   switch(curChar)
   {
      case 10:
         return jjStopAtPos(0, 10);
      default :
         return 1;
   }
}
private int jjMoveStringLiteralDfa0_4()
{
   switch(curChar)
   {
      case 10:
         return jjStopAtPos(0, 13);
      default :
         return 1;
   }
}
private int jjMoveStringLiteralDfa0_6()
{
   switch(curChar)
   {
      case 10:
         return jjStopAtPos(0, 17);
      default :
         return 1;
   }
}
private int jjMoveStringLiteralDfa0_5()
{
   switch(curChar)
   {
      case 42:
         return jjMoveStringLiteralDfa1_5(0x8000L);
      default :
         return 1;
   }
}
private int jjMoveStringLiteralDfa1_5(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      return 1;
   }
   switch(curChar)
   {
      case 47:
         if ((active0 & 0x8000L) != 0L)
            return jjStopAtPos(1, 15);
         break;
      default :
         return 2;
   }
   return 2;
}
private int jjMoveStringLiteralDfa0_3()
{
   return 1;
}
static final int[] jjnextStates = {
   88, 89, 91, 8, 92, 93, 43, 47, 48, 49, 28, 29, 31, 15, 16, 18, 
   62, 63, 64, 65, 66, 67, 69, 71, 73, 75, 78, 81, 51, 52, 53, 54, 
   55, 56, 58, 60, 9, 10, 13, 15, 16, 20, 18, 15, 16, 22, 18, 24, 
   26, 15, 16, 25, 18, 28, 29, 33, 31, 28, 29, 35, 31, 37, 39, 28, 
   29, 38, 31, 56, 58, 60, 67, 69, 71, 76, 77, 79, 80, 82, 84, 86, 
   90, 10, 13, 14, 27, 11, 12, 17, 19, 21, 23, 30, 32, 34, 36, 94, 
   95, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec2[i2] & l2) != 0L);
      default :
         if ((jjbitVec0[i1] & l1) != 0L)
            return true;
         return false;
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, "\173", "\175", "\133", "\135", "\50", "\51", 
"\72\72", "\72", "\73", "\54", "\77", "\56\56\56", "\75", "\52\75", "\57\75", "\45\75", 
"\53\75", "\55\75", "\74\74\75", "\76\76\75", "\46\75", "\136\75", "\174\75", 
"\174\174", "\46\46", "\174", "\136", "\46", "\75\75", "\41\75", "\74", "\76", "\74\75", 
"\76\75", "\74\74", "\76\76", "\53", "\55", "\52", "\57", "\45", "\53\53", "\55\55", 
"\176", "\41", "\56", "\55\76", "\56\52", "\55\76\52", "\141\165\164\157", 
"\142\162\145\141\153", "\143\141\163\145", "\143\141\164\143\150", "\143\150\141\162", 
"\143\157\156\163\164", "\143\157\156\164\151\156\165\145", "\144\145\146\141\165\154\164", 
"\144\145\154\145\164\145", "\144\157", "\144\157\165\142\154\145", "\145\154\163\145", 
"\145\156\165\155", "\145\170\164\145\162\156", "\146\154\157\141\164", "\146\157\162", 
"\146\162\151\145\156\144", "\147\157\164\157", "\151\146", "\151\156\154\151\156\145", 
"\155\165\164\141\142\154\145", "\145\170\160\154\151\143\151\164", 
"\144\171\156\141\155\151\143\137\143\141\163\164", "\163\164\141\164\151\143\137\143\141\163\164", 
"\162\145\151\156\164\145\162\160\162\145\164\137\143\141\163\164", "\143\157\156\163\164\137\143\141\163\164", "\164\171\160\145\151\144", 
"\167\143\150\141\162\137\164", "\142\157\157\154", "\151\156\164", "\154\157\156\147", "\156\145\167", 
"\160\162\151\166\141\164\145", "\160\162\157\164\145\143\164\145\144", "\160\165\142\154\151\143", 
"\162\145\144\145\143\154\141\162\145\144", "\162\145\147\151\163\164\145\162", "\162\145\164\165\162\156", 
"\163\150\157\162\164", "\163\151\147\156\145\144", "\163\151\172\145\157\146", 
"\163\164\141\164\151\143", "\163\164\162\165\143\164", "\143\154\141\163\163", 
"\164\171\160\145\156\141\155\145", "\163\167\151\164\143\150", "\164\145\155\160\154\141\164\145", 
"\145\170\160\157\162\164", "\164\150\151\163", "\164\162\171", "\164\171\160\145\144\145\146", 
"\165\156\151\157\156", "\165\156\163\151\147\156\145\144", "\166\151\162\164\165\141\154", 
"\166\157\151\144", "\166\157\154\141\164\151\154\145", "\167\150\151\154\145", 
"\157\160\145\162\141\164\157\162", "\164\162\165\145", "\146\141\154\163\145", "\164\150\162\157\167", null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, "\156\141\155\145\163\160\141\143\145", "\165\163\151\156\147", 
"\146\151\156\141\154\154\171", null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
   "LINE_NUMBER",
   "LINE_DIRECTIVE",
   "AFTER_LINE_DIRECTIVE",
   "IN_LINE_COMMENT",
   "IN_COMMENT",
   "PREPROCESSOR_OUTPUT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, 4, 5, 1, 1, 6, 2, 3, -1, 0, 0, -1, 0, -1, 0, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0xfffffffffff80001L, 0xffffffffffffffffL, 0x3fffffL, 
};
static final long[] jjtoSkip = {
   0x2bffeL, 0x0L, 0x0L, 
};
static final long[] jjtoMore = {
   0x54000L, 0x0L, 0x0L, 
};
protected JavaCharStream input_stream;
private final int[] jjrounds = new int[98];
private final int[] jjstateSet = new int[196];
private final StringBuilder jjimage = new StringBuilder();
private StringBuilder image = jjimage;
private int jjimageLen;
private int lengthOfMatch;
protected char curChar;
/** Constructor. */
public CPPParserTokenManager(JavaCharStream stream){
   if (JavaCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public CPPParserTokenManager(JavaCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(JavaCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 98; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(JavaCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 7 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }
   image = jjimage;
   image.setLength(0);
   jjimageLen = 0;

   for (;;)
   {
     switch(curLexState)
     {
       case 0:
         try { input_stream.backup(0);
            while (curChar <= 32 && (0x100000600L & (1L << curChar)) != 0L)
               curChar = input_stream.BeginToken();
         }
         catch (java.io.IOException e1) { continue EOFLoop; }
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_0();
         break;
       case 1:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_1();
         break;
       case 2:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_2();
         if (jjmatchedPos == 0 && jjmatchedKind > 11)
         {
            jjmatchedKind = 11;
         }
         break;
       case 3:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_3();
         if (jjmatchedPos == 0 && jjmatchedKind > 12)
         {
            jjmatchedKind = 12;
         }
         break;
       case 4:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_4();
         if (jjmatchedPos == 0 && jjmatchedKind > 14)
         {
            jjmatchedKind = 14;
         }
         break;
       case 5:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_5();
         if (jjmatchedPos == 0 && jjmatchedKind > 16)
         {
            jjmatchedKind = 16;
         }
         break;
       case 6:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_6();
         if (jjmatchedPos == 0 && jjmatchedKind > 18)
         {
            jjmatchedKind = 18;
         }
         break;
     }
     if (jjmatchedKind != 0x7fffffff)
     {
        if (jjmatchedPos + 1 < curPos)
           input_stream.backup(curPos - jjmatchedPos - 1);
        if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           matchedToken = jjFillToken();
       if (jjnewLexState[jjmatchedKind] != -1)
         curLexState = jjnewLexState[jjmatchedKind];
           return matchedToken;
        }
        else if ((jjtoSkip[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           SkipLexicalActions(null);
         if (jjnewLexState[jjmatchedKind] != -1)
           curLexState = jjnewLexState[jjmatchedKind];
           continue EOFLoop;
        }
        jjimageLen += jjmatchedPos + 1;
      if (jjnewLexState[jjmatchedKind] != -1)
        curLexState = jjnewLexState[jjmatchedKind];
        curPos = 0;
        jjmatchedKind = 0x7fffffff;
        try {
           curChar = input_stream.readChar();
           continue;
        }
        catch (java.io.IOException e1) { }
     }
     int error_line = input_stream.getEndLine();
     int error_column = input_stream.getEndColumn();
     String error_after = null;
     boolean EOFSeen = false;
     try { input_stream.readChar(); input_stream.backup(1); }
     catch (java.io.IOException e1) {
        EOFSeen = true;
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
        if (curChar == '\n' || curChar == '\r') {
           error_line++;
           error_column = 0;
        }
        else
           error_column++;
     }
     if (!EOFSeen) {
        input_stream.backup(1);
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
     }
     //throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
      return null;
   }
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      case 7 :
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                                     input_stream.backup(1);
         break;
      case 9 :
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
     try
     {
        beginLine = Integer.parseInt(image.toString());
     }
     catch(NumberFormatException e) { }
         break;
      case 12 :
         image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
     input_stream.adjustBeginLineColumn(beginLine, 1);
     input_stream.backup(1);
         break;
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
